import {CRAFT} from './craft-data.js';
import {openCraft} from './craft.js';
import {NightSky} from './night-sky.js';
import {StormFront} from './storm-front.js';
import {KITS,kit} from './kits.js';
import {ground} from './ground.js';
import {driveStep} from './driving.js';
import {capturePose,displayState} from './motion.js';
import {GPURenderer} from './gpu.js';
const {Renderer}=await import(/* @vite-ignore */ new URL('../../../extras/expedition/renderer.js',import.meta.url).href);
import {create,nearest,samples,reverseAvailable} from './simulation.js';
const {loadDelta}=await import(/* @vite-ignore */ new URL('../../../extras/expedition/regions.mjs',import.meta.url).href);
const nativeFetch=window.fetch.bind(window);window.fetch=(url,options)=>nativeFetch(url==='delta.json'?new URL('../../../extras/expedition/delta.json',import.meta.url):url,options);
const nightSky=new NightSky(document.querySelector('#night-sky'));const storm=new StormFront();const $=s=>document.querySelector(s),keys=new Set(),pointers=new Map(),input={drive:false,brake:false,steer:0};let selectedRover='sojourner',previousPose,state,course,gpu,current,mode='prototype',paused=false,last=0,acc=0,lastDraw=0,quality='balanced',light='day',measuring=false,redraw=true;
// Invisible, keyboard-accessible touch target follows the rendered rover, including jumps.
const lampToggle=document.createElement('button');lampToggle.id='rover-headlights';lampToggle.hidden=true;lampToggle.style.cssText='position:absolute;background:transparent;border:0;padding:0;z-index:2;min-width:44px;min-height:44px;touch-action:manipulation;cursor:pointer';document.body.append(lampToggle);
lampToggle.onclick=()=>{if(mode!=='prototype'||paused||measuring)return;gpu.headlightsOverride=!(gpu.lampStrength>0);redraw=true;};
function placeLampToggle(){const r=gpu?.roverScreenBounds;lampToggle.hidden=mode!=='prototype'||paused||measuring||!r;if(lampToggle.hidden)return;const w=Math.max(44,r.right-r.left),h=Math.max(44,r.bottom-r.top),rect=$('#gpu').getBoundingClientRect();lampToggle.style.left=`${rect.left+(r.left+r.right-w)/2}px`;lampToggle.style.top=`${rect.top+(r.top+r.bottom-h)/2}px`;lampToggle.style.width=`${w}px`;lampToggle.style.height=`${h}px`;lampToggle.setAttribute('aria-label','Rover headlights');lampToggle.setAttribute('aria-pressed',String(gpu.lampStrength>0));}
const poses={boost:[1120,470,Math.PI/2],ridge:[4200,-560,Math.PI],wall:[2580,210,0],gap:[2609,360,0],climb:[4200,400,0],bump:[943,700,0],delta:[2600,650,0],hill:[4200,-200,Math.PI],rocks:[5260,480,Math.PI/2]};
function sync(){const held=new Set(pointers.values());input.drive=keys.has('w')||keys.has('arrowup')||held.has('drive');input.brake=keys.has(' ')||keys.has('arrowdown')||keys.has('s')||held.has('brake');input.steer=(keys.has('d')||keys.has('arrowright')||held.has('right')?1:0)-(keys.has('a')||keys.has('arrowleft')||held.has('left')?1:0);}
function clear(){keys.clear();pointers.clear();sync();document.querySelectorAll('.active').forEach(b=>b.classList.remove('active'));}
function lighting(){state.solar=light==='night'?{east:0,north:0,up:-1,elevation:-1.57,azimuth:0,solarHour:0}:light==='dusk'?{east:-.65,north:.759,up:.05,elevation:.05,azimuth:-2.43,solarHour:18}:{east:-.45,north:.6,up:.66,elevation:.72,azimuth:-2.5,solarHour:12};$('#scene').style.background=light==='night'?'linear-gradient(#03060c,#080c14 65%,#151720)':light==='dusk'?'linear-gradient(#211c2c,#775751 58%,#745b51)':'linear-gradient(#75482f,#be8b62 53%,#b48059)';}
function pose(id){const p=poses[id];state=create('free',course,selectedRover);state.tune=kit(selectedRover);Object.assign(state,{x:p[0],y:p[1],heading:p[2],z:ground(p[0],p[1]),messageUntil:0});lighting();previousPose=capturePose(state,ground(state.x,state.y));acc=0;gpu?.reset(state);current.reset(state);clear();redraw=true;$('#location').textContent={boost:'Boost run',ridge:'Ridge jump',wall:'Tower camera',gap:'Split towers',climb:'Highland climb',bump:'Dune bump',delta:'Delta channels',hill:'Downhill',rocks:'Layered buttes'}[id];}
function select(value){if(value==='prototype'&&!gpu)return;const previous=mode==='prototype'?gpu:current;mode=value;const next=mode==='prototype'?gpu:current;if(previous?.camera)next.camera={...previous.camera};$('#gpu').hidden=mode!=='prototype';$('#night-sky').hidden=mode!=='prototype';$('#labels').hidden=mode!=='prototype';$('#current').hidden=mode!=='current';for(const b of document.querySelectorAll('[data-render]'))b.setAttribute('aria-pressed',String(b.dataset.render===mode));redraw=true;}
function pause(open=true){paused=open;lampToggle.hidden=true;clear();$('#options').hidden=!open;$('#menu').textContent=open?'▶':'Ⅱ';acc=0;if(state)previousPose=capturePose(state,ground(state.x,state.y));redraw=true;}
function render(dt){const opacity=storm.tick(paused||measuring?0:dt,state,()=>{gpu?.tracks.reset();});$('#dust-storm').style.opacity=mode==='prototype'?0:opacity*.85;$('#dust-storm').style.backgroundPosition=`${-storm.age*11}px ${-storm.age*3}px`;const start=performance.now(),shown=paused||measuring?state:displayState(previousPose,state,acc*60,ground(state.x,state.y));if(mode==='prototype'){gpu.quality=quality;gpu.storm=storm;gpu.draw(shown,dt,$('#labels'));nightSky.draw(gpu,shown);}else{current.quality=quality;current.draw(shown,course,dt);}placeLampToggle();return performance.now()-start;}
$('#choose-craft').onclick=()=>{pause(true);openCraft(selectedRover,id=>{$('#rover').value=id;$('#rover').dispatchEvent(new Event('change'));}).catch(e=>{$('#readings').textContent='Could not load craft viewer: '+e.message;});};
$('#sky-info').onclick=()=>{pause(true);let d=document.querySelector('#sky-dialog');if(!d){d=document.createElement('dialog');d.id='sky-dialog';d.style.cssText='max-width:460px;background:#10272b;color:#e5eee8;border:1px solid #688078;border-radius:14px;padding:22px';d.innerHTML='<h2>Night on Mars</h2><p>On a clear night, stars can shine above a dark landscape. Mars has two small moons, Phobos and Deimos. Their visibility depends on where and when you look.</p><p>Suspended dust hides stars and reduces visibility. After this storm passes, the haze clears in roughly forty seconds: much faster than real weather, so exploration stays fun.</p><p>The stars here are illustrative, not a dated sky chart. Polar nightglow is a real phenomenon, but is not shown over this Jezero-inspired landscape.</p><p><a style="color:#bce0ca" href="https://www.nasa.gov/missions/mars-science-laboratory/while-stargazing-on-mars-nasas-curiosity-rover-spots-earth-and-venus/" target="_blank" rel="noopener noreferrer">NASA sky observations ↗</a></p><form method="dialog"><button>Close</button></form>';document.body.append(d);}d.showModal();};
$('#storm-test').onclick=()=>{storm.start(state);pause(false);};
$('#rover').innerHTML=Object.entries(KITS).map(([id,k])=>`<option value="${id}">${k.name}</option>`).join('');function craftSummary(){const c=CRAFT.find(c=>c.id===selectedRover);$('#craft-summary').textContent=`${c.name} · ${c.site} · ${c.dates}`;}craftSummary();$('#rover').onchange=e=>{selectedRover=e.target.value;craftSummary();state.roverId=selectedRover;state.tune=kit(selectedRover);state.v=0;state.vz=0;state.air=false;state.z=ground(state.x,state.y);state.boost=0;state.jumpStart=null;previousPose=capturePose(state,state.z);gpu?.reset(state);clear();redraw=true;};
for(const b of document.querySelectorAll('[data-render]'))b.onclick=()=>select(b.dataset.render);for(const b of document.querySelectorAll('[data-pose]'))b.onclick=()=>{pose(b.dataset.pose);pause(false);};$('#menu').onclick=()=>pause(!paused);$('#resume').onclick=()=>pause(false);$('#quality').onchange=e=>{quality=e.target.value;redraw=true;};$('#light').onchange=e=>{light=e.target.value;lighting();redraw=true;};
for(const id of ['left','right','drive','brake']){const b=$('#'+id);b.onpointerdown=e=>{if(paused||measuring)return;e.preventDefault();b.setPointerCapture(e.pointerId);pointers.set(e.pointerId,id);b.classList.add('active');sync();};const release=e=>{pointers.delete(e.pointerId);if(![...pointers.values()].includes(id))b.classList.remove('active');sync();};b.onpointerup=release;b.onpointercancel=release;b.onlostpointercapture=release;}
addEventListener('keydown',e=>{if(e.target===lampToggle&&[' ','Enter'].includes(e.key))return;if(document.querySelector('dialog[open]'))return;if(e.key==='Escape'){pause(!paused);return;}const k=e.key.toLowerCase();if(['w','a','s','d','arrowup','arrowdown','arrowleft','arrowright',' '].includes(k)){e.preventDefault();if(!paused){keys.add(k);sync();}}});addEventListener('keyup',e=>{keys.delete(e.key.toLowerCase());sync();});addEventListener('blur',()=>pause(true));document.addEventListener('visibilitychange',()=>{if(document.hidden)pause(true)});for(const event of ['contextmenu','selectstart'])document.addEventListener(event,e=>e.preventDefault());addEventListener('resize',()=>redraw=true);
function frame(t){const dt=Math.min(.05,(t-last)/1000||0);last=t;if(!measuring){if(!paused){acc+=dt;while(acc>=1/60){previousPose=capturePose(state,ground(state.x,state.y));driveStep(state,input,1/60,course);acc-=1/60;}if(t-lastDraw>=(quality==='performance'?32:0)){render(Math.min(.05,(t-lastDraw)/1000));lastDraw=t;}}else if(redraw)render(0);redraw=false;$('#brake').textContent=reverseAvailable(state)?'Reverse':'Brake';$('#note').textContent=state.boundary?'Turn back toward the study area':state.collecting>=0?'Scanning…':state.messageUntil>state.t?state.message:'';}requestAnimationFrame(frame);}
// Repeatable drawing workload, not a flight/score test. Waiting for completion includes GPU work.
async function benchmark(frames=60){if(measuring)return;measuring=true;const saved={state:structuredClone(state),mode,paused};pause(true);const controls=[...document.querySelectorAll('button,select')].map(b=>[b,b.disabled]);for(const [b]of controls)b.disabled=true;const rows=[];try{for(const renderer of ['current','prototype']){if(renderer==='prototype'&&!gpu)continue;select(renderer);for(const speed of [0,76,190]){pose('delta');state.heading=Math.PI/2;state.v=speed;gpu?.reset(state);current.reset(state);render(0);const times=[],intervals=[];let previous=performance.now();for(let i=0;i<frames;i++){await new Promise(requestAnimationFrame);const now=performance.now();if(i>0)intervals.push(now-previous);previous=now;state.x+=speed/60;state.z=ground(state.x,state.y);const start=performance.now();render(1/60);if(mode==='prototype')gpu.gl.finish();else current.ctx.getImageData(0,0,1,1);times.push(performance.now()-start);}times.sort((a,b)=>a-b);intervals.sort((a,b)=>a-b);rows.push({renderer,speed,medianMs:+times[Math.floor(times.length*.5)].toFixed(2),p95Ms:+times[Math.floor(times.length*.95)].toFixed(2),p95FrameMs:+intervals[Math.floor(intervals.length*.95)].toFixed(2)});$('#readings').textContent=rows.map(r=>`${r.renderer} · ${r.speed===0?'stopped':r.speed===76?'drive':'boost'}: ${r.medianMs} ms draw`).join('\n');}}return rows;}finally{state=saved.state;mode=saved.mode;select(mode);gpu?.reset(state);current.reset(state);measuring=false;for(const [b,disabled]of controls)b.disabled=disabled;pause(true);}}
$('#compare').onclick=async()=>{const b=$('#compare');b.disabled=true;$('#readings').textContent='Measuring the same scene…';try{const rows=await benchmark();$('#readings').textContent=rows.map(r=>`${r.renderer} · ${r.speed===0?'stopped':r.speed===76?'drive':'boost'}: ${r.medianMs} ms draw, ${r.p95FrameMs} ms frame (95th percentile)`).join('\n');}finally{b.disabled=false;}};
try{await loadDelta();const raw=await nativeFetch(new URL('../../../extras/expedition/course.json',import.meta.url)).then(r=>r.json()),path=document.createElementNS('http://www.w3.org/2000/svg','path');path.setAttribute('d',raw.path);const len=path.getTotalLength(),n=Math.ceil(len/4),route=Array.from({length:n},(_,i)=>{const p=path.getPointAtLength(i/n*len);return {x:p.x,y:p.y}}),gate=p=>({x:p[0],y:p[1],dx:1,dy:0,i:nearest(route,...p).i});course={route,gates:raw.gates.map(gate),finish:gate(raw.start)};current=new Renderer($('#current'),null);try{gpu=new GPURenderer($('#gpu'));}catch(e){console.warn(e);mode='current';$('[data-render=prototype]').disabled=true;$('#readings').textContent=e.message;}pose('delta');select(mode);$('#gpu').addEventListener('webglcontextlost',e=>{e.preventDefault();select('current');gpu=null;$('[data-render=prototype]').disabled=true;$('#readings').textContent='Graphics context lost. Current renderer is available; reload to retry the prototype.';pause(true);});$('#loading').hidden=true;requestAnimationFrame(frame);
window.__marsPOC={get state(){return state},get mode(){return mode},get gpu(){return gpu},get input(){return input},pose,select,pause,benchmark,course,get storm(){return storm},get measuring(){return measuring}};
}catch(e){$('#loading').innerHTML='<b>Could not prepare the preview.</b><p></p>';$('#loading p').textContent=e.message;console.error(e);}
