import {KITS} from './kits.js';
// Surface operating dates, not launch dates. Real mass does not alter ASTRA's driving physics.
export const CRAFT=[
 {id:'sojourner',site:'Ares Vallis',dates:'1997',mass:'10.5 kg',model:'sojourner-study.glb',credit:'Shape study · detailed model pending',source:'https://science.nasa.gov/mission/mars-pathfinder/',about:'A microwave-sized explorer that proved a rover could drive on Mars. Sojourner examined rocks on an ancient floodplain while communicating through the Pathfinder lander.',power:'Solar panels',discovery:'Rocks and soil offered clues to a landscape shaped by ancient floods.'},
 {id:'spirit',site:'Gusev Crater',dates:'2004–2010',mass:'≈185 kg',model:'mer.glb',credit:'NASA / JPL-Caltech · twin rover design',source:'https://science.nasa.gov/mission/mer-spirit/',about:'Spirit climbed the Columbia Hills after landing inside Gusev Crater. Its discoveries helped reveal a wetter past, including evidence of ancient hot-water activity.',power:'Solar panels',discovery:'Silica-rich soil pointed to past hot springs or steam vents.'},
 {id:'opportunity',site:'Meridiani Planum',dates:'2004–2018',mass:'≈185 kg',model:'mer.glb',credit:'NASA / JPL-Caltech · twin rover design',source:'https://science.nasa.gov/mission/mer-opportunity/',about:'Opportunity explored for more than fourteen years. A mission planned for ninety Martian days became a long journey through evidence of ancient water.',power:'Solar panels',discovery:'Small mineral spheres nicknamed “blueberries” helped reveal groundwater activity.'},
 {id:'curiosity',site:'Gale Crater',dates:'2012–present',mass:'899 kg',model:'curiosity.glb',credit:'NASA / JPL-Caltech',source:'https://science.nasa.gov/mission/msl-curiosity/',about:'Curiosity is a mobile chemistry laboratory exploring Gale Crater and Mount Sharp. Its instruments study rocks to understand whether ancient Mars could have supported microbial life.',power:'Radioisotope generator',discovery:'Ancient lake sediments preserved evidence of habitable conditions.'},
 {id:'perseverance',site:'Jezero Crater',dates:'2021–present',mass:'1,025 kg',model:'perseverance.glb',credit:'NASA / JPL-Caltech',source:'https://science.nasa.gov/mission/mars-2020-perseverance/',about:'Perseverance explores an ancient lake basin and river delta. It searches for signs of past microbial life and seals rock samples for possible future study on Earth.',power:'Radioisotope generator',discovery:'Layered delta rocks preserve clues to water flowing into an ancient lake.'},
].map(c=>({...c,name:KITS[c.id].name}));
