/** Shared instructions for the current Moon/Gale gesture parser. */
export function rideHelp(vehicle='scooter'){
 const ski=vehicle==='ski';
 return `<p><b>Move:</b> ${ski?'Drive / Boost':'Go'}: W / ↑ / Space. Steer: A / D or ← / →. Brake: Shift / ↓.${ski?'':' Reverse: S.'}</p>
 <p><b>Hop / descend:</b> Double-tap Brake to hop on the ground or jolt downward in the air. Repeat pairs for more downward thrust. Jolts cannot interrupt a trick. Hold Brake with left/right to redirect your flight, even during tricks.</p>
 <p><b>Grab:</b> Press directions, then hold ${ski?'Drive':'Go'} (labelled Trick in the air). Release before landing. After release, a fresh direction + Trick starts the next grab immediately. Holding earns points.</p>
 <p><b>Flip:</b> Double-tap Trick within 0.32 seconds for a committed move. It finishes its animation whether you hold or release. Leave enough airtime to complete it.</p>
 <details><summary>Trick combinations</summary><p>Up to four direction presses count within one second. Overlapping holds and release order do not change the sequence. The first Trick press captures it; the quick second press selects its flip variant. Inputs during a held grab or committed animation do not queue another move.</p><p>L: Side grab / ${ski?'Blade whip':'Tailwhip'}<br>LL: Tail grab / Backflip<br>LR: Nose grab / Corkscrew<br>LLL: Tuck grab / Double backflip<br>LLR: Superman / Flip whip<br>LRL: Cross grab / ${ski?'Blade rewind':'Whip rewind'}<br>LRR: Rocket grab / 720 spin</p><p>R-first sequences mirror the same moves. LRLR + Trick–Trick: ${ski?'Red Planet Rodeo, a triple corkscrew with spinning blades':'The 9000, fifty full rider-and-scooter spins'}.</p></details>
 ${ski?'<p>Clean landings bank the combo. Held grabs and unfinished tricks lose it. No Manual on skis.</p>':`<details><summary>Manual &amp; combos</summary><p>While moving on the ground, double-tap Go with all other controls released. In the air, the same gesture arms a landing Manual only when too low to start a trick. It must be your last input before landing; it cannot arm during a trick.</p><p>Left/right balance. Hold Brake to steer instead, without braking; release Brake to balance again. Stopping keeps the Manual but makes balancing harder. Any airtime ends the Manual and keeps the combo alive. Double-tap Go again to arm the next Manual.</p><p>Free roam and the two-minute run share controls. Clean landings bank the combo; unfinished tricks and lost balance lose it. Collect M-O-O-N for a bonus. At 0:00, finish your active combo.</p></details>`}`;
}
