const DB='astra-jezero-photographs';
function database(){return new Promise((resolve,reject)=>{const r=indexedDB.open(DB,1);r.onupgradeneeded=()=>r.result.createObjectStore('photos',{keyPath:'id'});r.onsuccess=()=>resolve(r.result);r.onerror=()=>reject(r.error);});}
export async function storePhoto(blob,title,meta={}){
 const dataURL=await new Promise((resolve,reject)=>{const r=new FileReader();r.onload=()=>resolve(r.result);r.onerror=()=>reject(r.error);r.readAsDataURL(blob);});
 const db=await database();try{return await new Promise((resolve,reject)=>{const tx=db.transaction('photos','readwrite'),store=tx.objectStore('photos'),item={id:crypto.randomUUID(),title,dataURL,date:new Date().toISOString(),world:'Mars',worldId:'mars',kind:'field',...meta},count=store.count();count.onsuccess=()=>{if(count.result>=100){reject(Error('Photo album full (100 photographs).'));tx.abort();}else store.put(item);};tx.oncomplete=()=>resolve(item);tx.onerror=()=>reject(tx.error);tx.onabort=()=>reject(tx.error??Error('Photograph storage aborted'));});}finally{db.close();}
}
export function readPostcards(storage=localStorage){try{const list=JSON.parse(storage.getItem('lander.postcards')??'[]');return Array.isArray(list)?list.filter(p=>p&&typeof p.img==='string').map(p=>({id:p.ts,title:p.site,world:p.world,worldId:p.worldId,kind:p.variant==='collector'?'collector':'landing',dataURL:p.img,back:p.back,date:new Date(p.ts).toISOString(),postcard:true})):[];}catch{return [];}}
export async function readPhotos(){const cards=readPostcards();const db=await database();try{return await new Promise((resolve,reject)=>{const r=db.transaction('photos').objectStore('photos').getAll();r.onsuccess=()=>resolve([...r.result.map(p=>({world:'Mars',worldId:'mars',kind:'field',...p})),...cards].sort((a,b)=>Date.parse(b.date)-Date.parse(a.date)));r.onerror=()=>reject(r.error);});}finally{db.close();}}
export async function deletePhoto(id,postcard=false){if(postcard){const list=JSON.parse(localStorage.getItem('lander.postcards')??'[]');localStorage.setItem('lander.postcards',JSON.stringify(list.filter(p=>p.ts!==id)));return;}const db=await database();try{return await new Promise((resolve,reject)=>{const tx=db.transaction('photos','readwrite');tx.objectStore('photos').delete(id);tx.oncomplete=resolve;tx.onerror=()=>reject(tx.error);});}finally{db.close();}}
