import {readPhotos,deletePhoto} from './store.js';
let photos=[],urls=[];const $=s=>document.querySelector(s);
$('#close').onclick=()=>parent!==window?parent.postMessage({type:'astra-album-close',token:new URLSearchParams(location.search).get('albumToken')},location.origin):history.back();
addEventListener('keydown',e=>{if(e.key==='Escape')$('#close').click();});
$('#planet').onchange=render;
async function load(){try{photos=await readPhotos();const current=$('#planet').value;$('#planet').replaceChildren(new Option('All planets',''),...[...new Set(photos.map(p=>p.world??'Other'))].sort().map(w=>new Option(w,w)));$('#planet').value=current;render();}catch{$('#status').textContent='Photo storage is unavailable in this browser.';}}
function render(){for(const u of urls)URL.revokeObjectURL(u);urls=[];$('#photos').replaceChildren();const visible=photos.filter(p=>!$('#planet').value||p.world===$('#planet').value);$('#status').textContent=visible.length?`${visible.length} saved photographs and postcards`:'No photographs yet.';
 for(const p of visible){const f=document.createElement('figure'),img=new Image(),caption=document.createElement('figcaption'),nav=document.createElement('nav'),download=document.createElement('a'),remove=document.createElement('button');let back=false;const u=p.dataURL??URL.createObjectURL(p.blob);if(!p.dataURL)urls.push(u);img.src=u;img.alt=p.title;img.loading='lazy';caption.textContent=`${p.world} · ${p.title} · ${p.kind??'field'} · ${new Date(p.date).toLocaleDateString()}`;download.href=u;download.download=`${p.world}-${p.id}.jpg`;download.textContent='Download';remove.textContent='Delete';remove.onclick=async()=>{if(!confirm('Delete this saved image from this browser?'))return;try{await deletePhoto(p.id,p.postcard);await load();}catch{$('#status').textContent='Could not delete photograph.';}};if(p.back){const flip=document.createElement('button');flip.textContent='Flip';flip.onclick=()=>{back=!back;img.src=back?p.back:u;download.href=img.src;};nav.append(flip);}nav.append(download,remove);f.append(img,caption,nav);$('#photos').append(f);}
}load();
