// Repositionable live inset; swiping beyond either edge stows it without stopping updates.
export class MiniMap {
 constructor(button,handle,onOpen,onChange){Object.assign(this,{button,handle,onChange});this.state={enabled:true,x:null,y:null,side:null};let drag=null,suppress=0;
 button.title='Tap to open. Drag to move; swipe to an edge to hide.';button.style.touchAction='none';button.addEventListener('pointerdown',e=>{if(e.button!==0)return;const r=button.getBoundingClientRect();drag={id:e.pointerId,x:e.clientX,y:e.clientY,left:r.left,top:r.top,moved:false};button.setPointerCapture(e.pointerId);e.stopPropagation();});
 button.addEventListener('pointermove',e=>{if(!drag||e.pointerId!==drag.id)return;const dx=e.clientX-drag.x,dy=e.clientY-drag.y;if(Math.hypot(dx,dy)>6)drag.moved=true;if(!drag.moved)return;e.preventDefault();button.style.left=drag.left+dx+'px';button.style.top=Math.max(8,Math.min(innerHeight-button.offsetHeight-8,drag.top+dy))+'px';button.style.bottom='auto';});
 const finish=e=>{if(!drag||e.pointerId!==drag.id)return;if(drag.moved){suppress=performance.now()+500;const r=button.getBoundingClientRect();this.state.side=r.left< -r.width*.25?'left':r.right>innerWidth+r.width*.25?'right':null;this.state.x=Math.max(0,Math.min(1,r.left/Math.max(1,innerWidth-r.width)));this.state.y=Math.max(0,Math.min(1,r.top/Math.max(1,innerHeight-r.height)));this.layout();onChange();}drag=null;};button.addEventListener('pointerup',finish);button.addEventListener('pointercancel',finish);button.addEventListener('lostpointercapture',finish);
 button.onclick=()=>{if(performance.now()>suppress)onOpen();};handle.onclick=()=>{this.state.side=null;this.layout();onChange();};addEventListener('resize',()=>this.layout());
 }
 restore(s={}){this.state={enabled:s.enabled!==false,x:Number.isFinite(s.x)?Math.max(0,Math.min(1,s.x)):null,y:Number.isFinite(s.y)?Math.max(0,Math.min(1,s.y)):null,side:['left','right'].includes(s.side)?s.side:null};this.layout();}
 layout(){const {button:b,handle:h,state:s}=this;b.hidden=!s.enabled;h.hidden=!s.enabled||!s.side;if(!s.enabled)return;const w=b.offsetWidth,v=b.offsetHeight;if(s.x===null){const r=b.getBoundingClientRect();s.x=r.left/Math.max(1,innerWidth-w);s.y=r.top/Math.max(1,innerHeight-v);}const top=Math.max(8,Math.min(innerHeight-v-8,s.y*(innerHeight-v)));b.style.bottom='auto';b.style.top=top+'px';b.style.left=s.side==='left'?(-w-4)+'px':s.side==='right'?(innerWidth+4)+'px':Math.max(8,Math.min(innerWidth-w-8,s.x*(innerWidth-w)))+'px';b.setAttribute('aria-hidden',String(!!s.side));b.tabIndex=s.side?-1:0;h.style.top=Math.max(8,Math.min(innerHeight-44,top+v/2-22))+'px';h.style.left=s.side==='right'?'auto':'0';h.style.right=s.side==='right'?'0':'auto';h.textContent=s.side==='right'?'‹':'›';}
}
