import {toGame} from './terrain.js';
import {seitahPhoto,rimPhoto,falbreenPhoto} from './tour-photos.js';
const site=(id,name,e,n,fact,detail,source,cameraReference)=>({id,name,kind:'site',...toGame(e,n),fact,detail,source,cameraReference,image:'./assets/jezero-relief.png',imageType:'map',imageAlt:'Measured elevation relief of the expanded western Jezero world',imageDescription:'Supporting elevation map of the playable region, not a rover photograph.',imageCredit:'USGS CTX / HiRISE elevation products; ASTRA relief map',researchDetail:'Rover-area reference from the pinned executed traverse. Pickup position is authored nearby, not a solved camera pose or feature centroid. No new hero photograph is approved.'});
export const worldDiscoveries=[
 site('bright-angel','Bright Angel',-5687.90,2081.28,'Bright Angel exposes light-toned rocks beside the ancient Neretva Vallis river channel. Its different rock character gives scientists another piece of Jezero\u2019s history.','Perseverance reached this area in June 2024 after entering the channel to bypass rougher boulder terrain. Look for the contrast between the pale outcrops and the surrounding channel slopes.','https://www.jpl.nasa.gov/news/nasas-perseverance-fords-an-ancient-river-to-reach-science-target/','54_0'),
 site('western-rim','Jezero rim',-7673.12,-205.81,'Perseverance reached the top of Jezero\u2019s rim in December 2024, leaving the crater interior behind for a new chapter of exploration.','Turn back toward the east to see how the crater floor, delta and inlet fit together. The rim connects the landscape explored inside Jezero with the terrain beyond it.', 'https://www.nasa.gov/missions/mars-2020-perseverance/perseverance-rover/nasas-perseverance-rover-reaches-top-of-jezero-crater-rim/','64_0'),
 site('falbreen','Falbreen',-8548.59,-504.80,'Falbreen lies beyond Jezero\u2019s rim, in terrain that may preserve rocks older than the crater itself.','Perseverance photographed this area in May 2025. The journey did not end at the rim: exploring these older landscapes helps extend the story beyond the ancient lake and delta.', 'https://www.nasa.gov/missions/mars-2020-perseverance/perseverance-rover/nasas-perseverance-rover-captures-mars-vista-as-clear-as-day/','74_0'),
 {...site('neretva-vallis','Neretva Vallis',-5139.08,1761.12,'Neretva Vallis once carried water into Jezero. Billions of years later, its channel offered Perseverance a way around difficult boulder terrain on the approach to Bright Angel.','On sol 1155, May 20, 2024, Mastcam-Z recorded this view of the channel. Compare the sandy floor, scattered blocks and sloping valley wall. A route shaped by ancient water became part of a modern rover journey.','https://maps.planet.fu-berlin.de/jezero/360/38','52_2644'),
  ...toGame(-5144.08,1711.12),focus:toGame(-5480,1850),image:'./assets/neretva-sol1155.jpg',imageType:'photo',capturedAt:'2024-05-20',
  imageAlt:'Real Mastcam-Z view of Neretva Vallis with a sandy channel floor, scattered rocks and a layered valley wall',
  imageDescription:'Framed perspective from Mastcam-Z panorama 38, sol 1155, Z48, enhanced left-eye mosaic. Enhanced color is not a natural-color reference. This is the rover photograph, not the separate orbital-data reconstruction in the ESA map.',
  imageCredit:'NASA/JPL-Caltech/ASU/MSSS; panorama via FU Berlin. Bell III et al. (2025), LPSC 1719.',
  researchDetail:'Camera-area reference 52_2644, sol 1154 (-5139.08 m east, 1761.12 m north), is the last pinned waypoint before this mosaic. The pickup is authored 50.25 m south-southwest on gentler ground. The focus is authored along the channel; rover heading is not treated as lens heading. This is an approximate lookout, not a solved photographic pose.'},
];
for(const [id,photo]of [['western-rim',rimPhoto],['falbreen',falbreenPhoto]]){
 const p=worldDiscoveries.find(s=>s.id===id),map={...p};
 Object.assign(p,photo,{views:[map],researchDetail:`Camera-area reference ${p.cameraReference} from the pinned traverse. Approved perspective frame, approximate terrain match; viewer heading is not a verified compass bearing.`});
}
worldDiscoveries.push({...site('seitah-view','Seitah wheel tracks',2213.314604,-1793.687912,'Perseverance explored sand and exposed rocks at Seitah before returning toward the delta. Wheel tracks mark its passage through this early chapter of the mission.','Mastcam-Z photographed this scene on sols 181-182, August 23-24, 2021. Compare the low rocks, open sand and rover tracks. The rocks and tracks in the game are representative, not a surveyed reconstruction.','https://maps.planet.fu-berlin.de/jezero/360/8','7_0'),...seitahPhoto,researchDetail:'Camera-area anchor 7_0, sol 180: 2213.314604 m east, -1793.687912 m north. Approximate pickup position, not a solved camera pose. Separate from the later sol-201 crystals reference.'});
export const worldLocations=[{name:'Neretva Vallis',...toGame(-5115,1961)},{name:'Bright Angel',...toGame(-5688,2081)},{name:'Jezero rim',...toGame(-7673,-206)},{name:'Falbreen',...toGame(-8549,-505)},{name:'Western frontier',...toGame(-9724,-1430)}];
