import {WORLD_SCALE,MAP_SIZE} from './scale.js';
import {photos,photoDate} from './photos.js';
import {MiniMap} from './minimap.js';
import {mapBounds,raceSite,mapTarget,advanceEntry,CLOSE_RANGE,regionAt,reachableTarget,worldUnlocked} from './navigation.js';
import {loadArea,discoveries,SITE_VERSION} from './area.js';
import {regions,detailIndices,regionIdForDetail} from './regions.js';
import {landmarks} from './landmarks.js';
import {toMetres} from './terrain.js';
import {GPURenderer} from '../mars-renderer/gpu.js';
import {driveStep} from '../mars-renderer/driving.js';
import {kit,KITS,explorationKit,raceKit} from '../mars-renderer/kits.js';
import {capturePose,displayState} from '../mars-renderer/motion.js';
import {StormFront} from '../mars-renderer/storm-front.js';
import {NightSky} from '../mars-renderer/night-sky.js';
import {openCraft} from '../mars-renderer/craft.js';
import {box,triangle} from '../mars-renderer/geometry.js';
import {create,reverseAvailable} from '../mars-renderer/simulation.js';
const $=s=>document.querySelector(s),KEY='astra.jezero.'+SITE_VERSION;
const RACE_VERSION='smooth-2_5x-v5';
const kindLabel=(kind,long=false)=>kind==='region'?(long?'JEZERO / REGION':'REGION'):kind==='site'?(long?'JEZERO / VIEWPOINT':'VIEWPOINT'):kind==='history'?(long?'JEZERO / HISTORY STOP':'HISTORY STOP'):(long?'JEZERO / FACT':'FACT');
const SITE_COLORS={region:'#d5edc1',site:'#8fd5df',history:'#efc786',fact:'#e8a58e'};
const siteColor=p=>SITE_COLORS[p.kind]??SITE_COLORS.fact;
const clock=t=>`${Math.floor(t/60)}:${(t%60).toFixed(2).padStart(5,'0')}`;
let area,gpu,state,previous,paused=true,ready=false,welcome=true,last=0,acc=0,lastDraw=0,lastSave=0,lastMap=0,lastHud=0,dirty=true,selected='perseverance',quality='balanced',light='day',backTo=null,saveWarned=false;
const mods={kit:false};let stormsEnabled=true,raceExplorer=null;
const nav={target:null,labels:false};let cardSite=null,mapReturn=null,pendingJump=null;let entryTime=0,entryArmed=true;const observedInside=new Set();
const input={drive:false,brake:false,steer:0},keys=new Set(),pointers=new Map();
const progress={seenLandmarks:[],collected:[],regions:[],completedActivities:[],legacyBests:{},bests:{},rover:'perseverance',position:null};
const minimap=new MiniMap($('#mini-map-button'),$('#map-return'),()=>{mapReturn=null;openDialog('#map-dialog');},()=>save());
const storm=new StormFront(),sky=new NightSky($('#night-sky')),relief=new Image();relief.src=new URL('./assets/relief.webp',import.meta.url).href;
function readSave(){try{const s=JSON.parse(localStorage.getItem(KEY)||'null');if(!s||s.version!==SITE_VERSION)return;
 const coordinateRatio=WORLD_SCALE/(s.worldScale??1);for(const p of [s.position,s.navigation?.target])if(p){p.x*=coordinateRatio;p.y*=coordinateRatio;}
 progress.collected=Array.isArray(s.collected)?[...new Set(s.collected.filter(i=>(s.siteCatalog>=2||i===3)&&Number.isInteger(i)&&i>=0&&i<discoveries.length))]:[];
 progress.regions=Array.isArray(s.regions)?[...new Set(s.regions.filter(id=>regions.some(r=>(r.regionId??r.id)===id)))]:[];
 for(const i of progress.collected){const id=i===3?'kodiak':regionIdForDetail(i);if(id&&!progress.regions.includes(id))progress.regions.push(id);}
 progress.legacyBests={...s.legacyBests,...(s.raceVersion===RACE_VERSION?{}:Object.fromEntries(Object.entries(s.bests??{}).map(([id,time])=>[(s.raceVersion??'original')+':'+id,time])))};
 if(s.raceVersion===RACE_VERSION&&s.bests&&typeof s.bests==='object')for(const id of Object.keys(KITS))if(Number.isFinite(s.bests[id])&&s.bests[id]>0)progress.bests[id]=s.bests[id];
 progress.completedActivities=Array.isArray(s.completedActivities)?[...new Set(s.completedActivities.filter(id=>id===raceSite.id))]:[];
 // A saved record proves completion for players upgrading from the previous save shape.
 if((Object.keys(progress.bests).length||Object.keys(s.bests??{}).length)&&!progress.completedActivities.includes(raceSite.id))progress.completedActivities.push(raceSite.id);
 if(s.navigation?.target){const t=s.navigation.target;if(Number.isFinite(t.x)&&Number.isFinite(t.y)&&t.x>=0&&t.x<=MAP_SIZE&&t.y>=0&&t.y<=MAP_SIZE)nav.target=reachableTarget(t,area.bounds);}
 mods.kit=s.mods?.kit===true||s.mods?.speed===true||s.mods?.air===true;stormsEnabled=s.stormsEnabled!==false;minimap.restore(s.minimap);nav.labels=s.navigation?.labels===true;
 progress.seenLandmarks=Array.isArray(s.seenLandmarks)?[...new Set(s.seenLandmarks.filter(id=>landmarks.some(p=>p.id===id)))]:[];
 if(KITS[s.rover])selected=s.rover;
 if(['balanced','performance'].includes(s.quality))quality=s.quality;if(['day','dusk','night'].includes(s.light))light=s.light;
 if(s.position&&['x','y','heading'].every(k=>Number.isFinite(s.position[k]))){const p=s.position,b=area.bounds;if(p.x>b.minX+100&&p.x<b.width-100&&p.y>b.minY+100&&p.y<b.maxY-100)progress.position=p;}
 }catch{/* Corrupt or unavailable storage cannot prevent exploration. */}}
function save(){if(!ready)return;const position=state.mode==='free'&&!state.air&&!state.turnaround?{x:state.x,y:state.y,heading:state.heading}:progress.position;
 try{localStorage.setItem(KEY,JSON.stringify({version:SITE_VERSION,worldScale:WORLD_SCALE,siteCatalog:3,collected:progress.collected,regions:progress.regions,completedActivities:progress.completedActivities,bests:progress.bests,legacyBests:progress.legacyBests,raceVersion:RACE_VERSION,rover:raceExplorer??selected,position,quality,light,seenLandmarks:progress.seenLandmarks,navigation:nav,mods,stormsEnabled,minimap:minimap.state}));progress.position=position;}catch{if(!saveWarned){saveWarned=true;notify('Progress cannot be saved in this browser.');}}}
function notify(text,seconds=5){state.message=text;state.messageUntil=state.t+seconds;dirty=true;}
function sync(){const held=new Set(pointers.values());input.drive=keys.has('w')||keys.has('arrowup')||held.has('drive');input.brake=keys.has(' ')||keys.has('arrowdown')||keys.has('s')||held.has('brake');input.steer=(keys.has('d')||keys.has('arrowright')||held.has('right')?1:0)-(keys.has('a')||keys.has('arrowleft')||held.has('left')?1:0);}
function clearInput(){keys.clear();pointers.clear();sync();document.querySelectorAll('.controls .active').forEach(b=>b.classList.remove('active'));}
function lighting(){state.solar=light==='night'?{east:0,north:0,up:-1}:light==='dusk'?{east:-.65,north:.759,up:.05}:{east:-.45,north:.6,up:.66};$('#scene').style.background=light==='night'?'linear-gradient(#03060c,#080c14 65%,#151720)':light==='dusk'?'linear-gradient(#211c2c,#775751 58%,#745b51)':'linear-gradient(#75482f,#be8b62 53%,#b48059)';}
function resetAt(p=area.start,mode='free'){
 state=create(mode,area.course,selected);Object.assign(state,{x:p.x,y:p.y,heading:p.heading??-Math.PI*.35,z:area.ground(p.x,p.y),tune:mode==='trial'?raceKit(selected,true):explorationKit(selected,mods),collected:[...progress.collected],regions:[...progress.regions],messageUntil:0});
 previous=capturePose(state,state.z);gpu.reset(state);acc=0;clearInput();lighting();dirty=true;updateHud();
}
function closeDialogs(){for(const d of document.querySelectorAll('dialog[open]'))d.close();backTo=null;}
function setPause(value){paused=value;clearInput();acc=0;if(state)previous=capturePose(state,area.ground(state.x,state.y));$('#lamps').hidden=true;dirty=true;if(value)save();else if(document.activeElement instanceof HTMLElement)document.activeElement.blur();}
function openDialog(id,caller=null){closeDialogs();backTo=caller;setPause(true);$(id).showModal();if(id==='#pause-dialog')$('#resume').textContent='RESUME';if(id==='#map-dialog'){$('#site-labels').checked=nav.labels;drawMap();}if(id==='#notes-dialog')renderNotes();if(id==='#jump-dialog')renderJumpSites();syncMenuTabs();}
function closeSheet(){const back=backTo;if($('#map-dialog').open&&mapReturn){const r=mapReturn;mapReturn=null;showCard(r.site,r.caller,r.site.kind);notesReturn=r.notes;return;}closeDialogs();if(back)openDialog(back,back==='#notes-dialog'?notesReturn:back==='#map-dialog'&&mapReturn?'#discovery-dialog':null);else setPause(false);}
function restoreExplorer(){if(raceExplorer){selected=raceExplorer;raceExplorer=null;mods.kit=false;state.roverId=selected;state.tune=explorationKit(selected,mods);state.v=state.vz=0;state.air=false;state.z=area.ground(state.x,state.y);previous=capturePose(state,state.z);gpu.reset(state);}}
function explore(){restoreExplorer();welcome=false;$('#welcome').hidden=true;closeDialogs();state.mode='free';state.done=false;state.countdown=0;setPause(false);updateHud();save();}
function startLap(){raceExplorer??=selected;entryTime=0;entryArmed=false;$('#scene').classList.remove('race-transition');void $('#scene').offsetWidth;$('#scene').classList.add('race-transition');welcome=false;$('#welcome').hidden=true;closeDialogs();resetAt(area.start,'trial');setPause(false);}
function endLap(){restoreExplorer();state.mode='free';state.tune=explorationKit(selected,mods);state.done=false;state.countdown=0;state.time=0;notify('Explore freely');updateHud();save();}
function finishLap(){const time=state.time,old=progress.bests[selected];if(!old||time<old)progress.bests[selected]=time;if(!progress.completedActivities.includes(raceSite.id))progress.completedActivities.push(raceSite.id);mods.kit=false;
 $('#result-time').textContent=clock(time);$('#result-best').textContent=!old||time<old?'Your best in this rover':`Best · ${clock(old)}`;
 state.mode='free';state.done=false;state.countdown=0;state.v=0;openDialog('#result-dialog');updateHud();save();}
let currentRegion='';
function updateHud(){if(!state)return;const region=regionAt(state);if(region!==currentRegion){currentRegion=region;$('#region-name').textContent=region;}const racing=state.mode==='trial',counting=racing&&state.countdown>0,count=String(Math.ceil(state.countdown));$('#race-hud').hidden=!racing||counting;$('#timer').textContent=clock(state.time);const countdown=$('#race-countdown');countdown.hidden=!counting;if(counting&&countdown.textContent!==count)countdown.textContent=count;$('#brake').textContent=!state.air&&reverseAvailable(state,[])?'Reverse':'Brake';$('#entry-loading').hidden=paused||entryTime<=0;$('#entry-loading progress').value=entryTime;$('#toast').textContent=welcome?'':state.boundary?'Return toward Three Forks':state.messageUntil>state.t?state.message:'';}

let notesReturn=null;
function inspectPhoto(site,photo){$('#photo-title').textContent=site.name;$('#photo-image').src=new URL(photo.image,import.meta.url).href;$('#photo-image').alt=photo.imageAlt;$('#photo-date').textContent=photoDate(photo.capturedAt);$('#photo-description').textContent=photo.imageDescription??photo.imageAlt;$('#photo-credit').textContent=photo.imageCredit;$('#photo-source').href=photo.source;$('#photo-dialog').showModal();}
$('#photo-close').onclick=()=>$('#photo-dialog').close();
function showCard(p,caller,kind){if(caller==='#notes-dialog')notesReturn=backTo;
 cardSite=p;$('#discovery-dialog').dataset.kind=kind;
 $('#discovery-kind').textContent=kindLabel(kind,true);
 $('#discovery-title').textContent=p.name;$('#discovery-fact').textContent=p.fact;$('#discovery-detail').textContent=p.detail;
 $('.discovery-map-context').hidden=caller==='#notes-dialog';$('#discovery-map-note').textContent=p.locationNote??'Accessible discovery location';$('#discovery-map-button').setAttribute('aria-label',p.kind==='history'?'Open map for this accessible history stop; actual site is outside the playable map':'Open detailed discovery location map');
 const strip=$('#discovery-views');strip.replaceChildren();
 const views=photos(p);if(p.routeMap)views.push({image:'./assets/mission-route.svg',imageAlt:'Recorded rover route from the true landing site into Three Forks',imageDescription:'NASA drive vertices through sol 692. The circled landing site is outside the dashed playable boundary. This is a mission-history map, not a driving target.',imageCredit:'NASA Mars 2020 public map data · ASTRA map rendering',source:'https://science.nasa.gov/mission/mars-2020-perseverance/location-map/'});for(const [i,v]of views.entries()){const figure=document.createElement('figure'),button=document.createElement('button'),img=document.createElement('img'),caption=document.createElement('figcaption');button.type='button';button.setAttribute('aria-label','Open photograph '+(i+1)+' of '+p.name);img.src=new URL(v.image,import.meta.url).href;img.alt=v.imageAlt;if(!i)img.id='discovery-image';img.onerror=()=>{img.alt='Photograph unavailable — open for source details';};button.append(img);button.onclick=()=>inspectPhoto(p,v);caption.textContent=(v.iconic?'Iconic view · ':'')+photoDate(v.capturedAt);figure.append(button,caption);strip.append(figure);}
 $('#discovery-source').href=views[0].source;openDialog('#discovery-dialog',caller);strip.scrollLeft=0;drawCardMap();
 $('#discovery-continue').textContent=caller?'Back to Field Notes':state.mode==='trial'?'Resume time trial':'Continue exploring';
}
function showDiscovery(i,caller=null){const p=discoveries[i];if(p&&progress.collected.includes(i))showCard(p,caller,p.kind);}
function setMapTarget(x,y,w,h){const target=mapTarget(x,y,w,h,area.bounds),old=nav.target;const same=old&&Math.hypot((old.x-target.x)/MAP_SIZE*w,(old.y-target.y)/MAP_SIZE*h)<12;nav.target=same||Math.hypot(target.x-state.x,target.y-state.y)<=CLOSE_RANGE?null:target;save();drawMap();drawMap($('#mini-map'),true);dirty=true;}
$('#clear-target').onclick=()=>{nav.target=null;save();drawMap();drawMap($('#mini-map'),true);dirty=true;};
$('#map').onclick=e=>{const r=e.currentTarget.getBoundingClientRect();setMapTarget(e.clientX-r.left,e.clientY-r.top,r.width,r.height);};
let mapCursor={x:.5,y:.5};$('#map').onkeydown=e=>{const moves={ArrowLeft:[-.025,0],ArrowRight:[.025,0],ArrowUp:[0,-.025],ArrowDown:[0,.025]};if(moves[e.key]){e.preventDefault();mapCursor.x=Math.max(0,Math.min(1,mapCursor.x+moves[e.key][0]));mapCursor.y=Math.max(0,Math.min(1,mapCursor.y+moves[e.key][1]));$('#map').dataset.cursor=JSON.stringify(mapCursor);drawMap();}if(e.key==='Enter'){e.preventDefault();const r=$('#map').getBoundingClientRect();setMapTarget(mapCursor.x*r.width,mapCursor.y*r.height,r.width,r.height);}};
$('#map').onblur=()=>{delete $('#map').dataset.cursor;drawMap();};
function renderNotes(){
 const sites=detailIndices.filter(i=>progress.collected.includes(i)).length,raceDone=progress.completedActivities.includes('delta-trial'),complete=worldUnlocked(progress,detailIndices,regions.map(r=>r.regionId??r.id));$('#notes-progress').textContent=complete?'Three Forks complete · All regions, discoveries and the Delta circuit explored.':`${progress.regions.length} / ${regions.length} regions · ${sites} / ${detailIndices.length} discoveries · Delta circuit: ${raceDone?'complete':'finish a lap'}`;
 const noteRow=(p,known)=>{const entry=document.createElement('div'),row=document.createElement('button');entry.className='note-entry';entry.style.setProperty('--site-color',siteColor(p));row.className='note-row';row.dataset.kind=p.kind;const img=document.createElement('img'),type=document.createElement('small'),name=document.createElement('span');type.textContent=kindLabel(p.kind);name.textContent=known?p.name:'???';if(known){const v=photos(p)[0];img.src=new URL(v.image,import.meta.url).href;img.alt='';row.onclick=()=>showCard(p,'#notes-dialog',p.kind);}else{img.hidden=true;row.disabled=true;}row.append(img,type,name);entry.append(row);if(known){const actions=document.createElement('div');actions.className='note-actions';const target=document.createElement('button'),jump=document.createElement('button');target.textContent='Target on map';target.onclick=()=>targetSite(p);jump.textContent='Jump to site';jump.onclick=()=>requestJump(p,'#notes-dialog');actions.append(target,jump);entry.append(actions);}return entry;};
 $('#notes').replaceChildren(...regions.map(region=>{const id=region.regionId??region.id,known=progress.regions.includes(id),section=document.createElement('section');section.className='note-region';const head=document.createElement('div');head.className='note-region-head';const title=document.createElement('h3');title.textContent=known?region.name:'???';const count=document.createElement('small'),children=detailIndices.filter(i=>regionIdForDetail(i)===id);count.textContent=known?(children.length?`${children.filter(i=>progress.collected.includes(i)).length} / ${children.length} sites`:'REGION OVERVIEW'):'REGION';head.append(title,count);section.append(head,noteRow(region,known));if(known)for(const i of children)section.append(noteRow(discoveries[i],progress.collected.includes(i)));return section;}));
}
function raceMapBounds(){const xs=area.course.route.map(p=>p.x),ys=area.course.route.map(p=>p.y),pad=180;return {minX:Math.min(...xs)-pad,width:Math.max(...xs)+pad,minY:Math.min(...ys)-pad,maxY:Math.max(...ys)+pad};}
function mapPoint(p,w,h,b=mapBounds){return {x:(p.x-b.minX)/(b.width-b.minX)*w,y:(p.y-b.minY)/(b.maxY-b.minY)*h};}
function drawMap(c=$('#map'),mini=false){
 const rect=c.getBoundingClientRect(),w=Math.max(1,rect.width),h=Math.max(1,rect.height),dpr=Math.min(2,devicePixelRatio),bounds=mini&&state.mode==='trial'?raceMapBounds():mapBounds;c.width=w*dpr;c.height=h*dpr;const ctx=c.getContext('2d');ctx.scale(dpr,dpr);ctx.fillStyle='#8a6346';ctx.fillRect(0,0,w,h);if(relief.complete&&relief.naturalWidth){const sx=bounds.minX/MAP_SIZE*relief.naturalWidth,sy=bounds.minY/MAP_SIZE*relief.naturalHeight,sw=(bounds.width-bounds.minX)/MAP_SIZE*relief.naturalWidth,sh=(bounds.maxY-bounds.minY)/MAP_SIZE*relief.naturalHeight;ctx.drawImage(relief,sx,sy,sw,sh,0,0,w,h);}ctx.fillStyle='#1e242233';ctx.fillRect(0,0,w,h);
 const occupied=[];
 function mapLabel(text,q,offset){const tw=ctx.measureText(text).width;let chosen;for(const dy of [offset,...Array.from({length:10},(_,i)=>[(i+1)*14+offset,offset-(i+1)*14]).flat()]){const x=Math.max(tw/2+3,Math.min(w-tw/2-3,q.x)),y=Math.max(12,Math.min(h-4,q.y+dy)),r={x:x-tw/2-2,y:y-10,w:tw+4,h:13};if(!occupied.some(a=>r.x<a.x+a.w&&r.x+r.w>a.x&&r.y<a.y+a.h&&r.y+r.h>a.y)){chosen={x,y,r};break;}}if(!chosen)return;occupied.push(chosen.r);if(Math.abs(chosen.y-q.y)>18){ctx.strokeStyle='#e7dbb866';ctx.lineWidth=.5;ctx.beginPath();ctx.moveTo(q.x,q.y);ctx.lineTo(chosen.x,chosen.y-5);ctx.stroke();}ctx.fillText(text,chosen.x,chosen.y);}
 c.dataset.geologyVisible='false';c.dataset.sitesVisible='true';c.dataset.raceVisible=String(state.mode==='trial');c.dataset.targetVisible=String(!!nav.target);c.dataset.stormVisible=String(storm.age>=0);
 if(storm.age>=0){const cols=mini?22:36,rows=mini?20:32;for(let iy=0;iy<rows;iy++)for(let ix=0;ix<cols;ix++){const x=bounds.minX+(ix+.5)/cols*(bounds.width-bounds.minX),y=bounds.minY+(iy+.5)/rows*(bounds.maxY-bounds.minY),density=storm.density(x,y);if(density>.03){ctx.fillStyle=`rgba(91,65,49,${Math.min(.55,density*.5)})`;ctx.fillRect(ix*w/cols,iy*h/rows,w/cols+1,h/rows+1);}}}
 if(state.mode==='trial'){ctx.strokeStyle='#ddb17a';ctx.lineWidth=mini?9:12;ctx.lineJoin='round';ctx.beginPath();area.course.route.forEach((p,i)=>{const q=mapPoint(p,w,h,bounds);i?ctx.lineTo(q.x,q.y):ctx.moveTo(q.x,q.y);});ctx.closePath();ctx.stroke();for(const p of [...area.course.gates,area.course.finish]){const q=mapPoint(p,w,h,bounds);ctx.beginPath();ctx.arc(q.x,q.y,mini?2.5:3.5,0,Math.PI*2);ctx.fillStyle='#e6f0c8';ctx.fill();}}
 const flag=mapPoint(raceSite,w,h,bounds);ctx.font=`${mini?12:16}px system-ui`;ctx.textAlign='center';ctx.fillStyle='#fff';ctx.fillText('🏁',flag.x,flag.y+5);
 if(!mini&&c.dataset.cursor){const cursor=JSON.parse(c.dataset.cursor);ctx.strokeStyle='#fff8';ctx.lineWidth=1;ctx.strokeRect(cursor.x*w-4,cursor.y*h-4,8,8);}
 for(const p of regions){const id=p.regionId??p.id,q=mapPoint(p,w,h,bounds),known=progress.regions.includes(id);if(q.x<-12||q.x>w+12||q.y<-12||q.y>h+12)continue;ctx.fillStyle=known?'#d5edc1':'#efe2bc';ctx.beginPath();ctx.arc(q.x,q.y,mini?3.4:5,0,Math.PI*2);ctx.fill();ctx.strokeStyle='#17322e';ctx.lineWidth=1;ctx.stroke();ctx.font=`${mini?8:10}px system-ui`;ctx.fillStyle='#f5ead1';mapLabel(known?p.name:'???',q,mini?12:15);}
 for(const i of detailIndices){const p=discoveries[i],id=regionIdForDetail(i);if(!progress.regions.includes(id))continue;const q=mapPoint(p,w,h,bounds);if(q.x<-8||q.x>w+8||q.y<-8||q.y>h+8)continue;ctx.fillStyle=siteColor(p);ctx.globalAlpha=mini?.9:1;if(p.kind==='history')ctx.fillRect(q.x-(mini?3:4),q.y-(mini?3:4),mini?6:8,mini?6:8);else{ctx.beginPath();ctx.arc(q.x,q.y,mini?2.8:4,0,Math.PI*2);ctx.fill();}ctx.globalAlpha=1;if(!mini&&nav.labels){ctx.font=`${w<260?8:10}px system-ui`;ctx.textAlign='center';mapLabel(progress.collected.includes(i)?(p.mapName??p.name):'???',q,12);}}
 const rover=mapPoint(state,w,h,bounds);ctx.save();ctx.translate(rover.x,rover.y);ctx.rotate(state.heading);ctx.fillStyle='#e2ffe3';ctx.strokeStyle='#16332d';ctx.lineWidth=1;ctx.beginPath();ctx.moveTo(0,-6);ctx.lineTo(4,4);ctx.lineTo(0,2);ctx.lineTo(-4,4);ctx.closePath();ctx.fill();ctx.stroke();ctx.restore();
 if(!mini&&mapReturn){const q=mapPoint(mapReturn.site,w,h,bounds);ctx.strokeStyle='#fff0ba';ctx.lineWidth=1;ctx.beginPath();ctx.arc(q.x,q.y,8,0,Math.PI*2);ctx.stroke();}
 if(nav.target){const q=mapPoint(nav.target,w,h,bounds);ctx.strokeStyle='#c6f5df';ctx.lineWidth=1;ctx.beginPath();ctx.arc(q.x,q.y,mini?2:3,0,Math.PI*2);ctx.moveTo(q.x-5,q.y);ctx.lineTo(q.x+5,q.y);ctx.moveTo(q.x,q.y-5);ctx.lineTo(q.x,q.y+5);ctx.stroke();}
 if(!mini)$('#clear-target').hidden=!nav.target;
}
$('#site-labels').onchange=e=>{nav.labels=e.target.checked;save();drawMap();};
function drawCardMap(){const c=$('#discovery-map'),w=240,h=240;c.width=w*2;c.height=h*2;const ctx=c.getContext('2d');ctx.scale(2,2);ctx.fillStyle='#896342';ctx.fillRect(0,0,w,h);if(relief.complete&&relief.naturalWidth)ctx.drawImage(relief,0,0,w,h);const q=mapPoint(cardSite,w,h);ctx.strokeStyle='#fff0ba';ctx.lineWidth=2;ctx.beginPath();ctx.arc(q.x,q.y,12,0,Math.PI*2);ctx.stroke();ctx.fillStyle='#fff0ba';ctx.beginPath();ctx.arc(q.x,q.y,2,0,Math.PI*2);ctx.fill();}
$('#discovery-map-button').onclick=()=>{mapReturn={caller:backTo,notes:notesReturn,site:cardSite};nav.labels=true;openDialog('#map-dialog','#discovery-dialog');};
function gateGeometry(){const v=[];for(const side of [-1,1]){box(v,side*46-1,-1,0,2,2,25,[.63,.83,.67]);triangle(v,[side*46,0,25],[side*46+side*10,0,21],[side*46,0,17],[.76,.91,.7]);}return gpu.upload(new Float32Array(v));}
let posts;
function wayfinding(){
 const c=$('#wayfinding'),w=c.clientWidth,h=c.clientHeight;c.width=w;c.height=h;const ctx=c.getContext('2d');
 if(state.mode==='free'&&Math.hypot(state.x-raceSite.x,state.y-raceSite.y)<1000){ctx.strokeStyle='#cfe8b377';ctx.lineWidth=1;ctx.beginPath();let pen=false;for(let i=0;i<=48;i++){const a=i/48*Math.PI*2,x=raceSite.x+Math.cos(a)*raceSite.radius,y=raceSite.y+Math.sin(a)*raceSite.radius,q=gpu.project(x,y,area.ground(x,y)+.5);if(q.depth<=4){pen=false;continue;}if(pen)ctx.lineTo(q.x,q.y);else ctx.moveTo(q.x,q.y);pen=true;}ctx.stroke();}
 const racing=state.mode==='trial';c.dataset.direction='none';if(!racing){if(!nav.target||paused||welcome)return;const a=Math.atan2(nav.target.x-state.x,-(nav.target.y-state.y))-gpu.camera.h,angle=Math.atan2(Math.sin(a),Math.cos(a)),halfView=Math.atan(w/(2*Math.min(w*.95,h*.9)));if(Math.abs(angle)<=halfView)return;const right=angle>0,x=right?w-22:22,y=h*.44;c.dataset.direction=right?'right':'left';ctx.strokeStyle='#ddedd1';ctx.lineWidth=2;ctx.beginPath();ctx.moveTo(x+(right?-4:4),y-7);ctx.lineTo(x+(right?3:-3),y);ctx.lineTo(x+(right?-4:4),y+7);ctx.stroke();return;}
 const target=racing?(area.course.gates[state.nextGate]??area.course.finish):nav.target,ground=(area.visualGround??area.ground)(target.x,target.y);
 // The active checkpoint is a physical-looking pair of flags. The course
 // surface—not floating text, distance counters or arrows—guides the player.
 if(racing){gpu.mesh(posts,[target.x,target.y,ground,target.heading],7);return;}
 const meters=Math.round(Math.hypot(target.x-state.x,target.y-state.y)/4);
 ctx.font='600 14px system-ui';ctx.textAlign='center';ctx.fillStyle='#e6f2cc';ctx.strokeStyle='#182f2b';ctx.lineWidth=4;
 const label=target.name+` · ${meters} m`;
 const angle=Math.atan2(target.x-state.x,-(target.y-state.y))-gpu.camera.h,dx=Math.sin(angle),dy=-Math.cos(angle),cx=w/2,cy=h/2,r=Math.min(w*.35,h*.29),x=cx+dx*r,y=cy+dy*r;ctx.save();ctx.translate(x,y);ctx.rotate(angle);ctx.beginPath();ctx.moveTo(0,-12);ctx.lineTo(8,7);ctx.lineTo(-8,7);ctx.closePath();ctx.stroke();ctx.fill();ctx.restore();ctx.strokeText(label,w/2,h>500?155:87);ctx.fillText(label,w/2,h>500?155:87);
}
function placeLamps(){const r=gpu.roverScreenBounds,b=$('#lamps');b.hidden=paused||welcome||!r;if(b.hidden)return;const w=Math.max(44,r.right-r.left),h=Math.max(44,r.bottom-r.top);b.style.left=(r.left+r.right-w)/2+'px';b.style.top=(r.top+r.bottom-h)/2+'px';b.style.width=w+'px';b.style.height=h+'px';b.setAttribute('aria-pressed',String(gpu.lampStrength>0));}
function draw(dt){gpu.quality=quality;gpu.storm=storm;const shown=paused?state:displayState(previous,state,acc*60,area.ground(state.x,state.y));gpu.draw(shown,dt,$('#labels'));sky.draw(gpu,shown);wayfinding();placeLamps();}

function step(dt){previous=capturePose(state,area.ground(state.x,state.y));driveStep(state,input,dt,area.course,{...area.driveArea,roverHandling:true,airControl:state.tune.boostKit,boostKit:state.tune.boostKit});if(stormsEnabled)storm.tick(dt,state,()=>gpu.tracks.reset());
 for(const p of regions){const id=p.regionId??p.id,key='region:'+id,distance=Math.hypot(state.x-p.x,state.y-p.y);if(distance>CLOSE_RANGE)observedInside.delete(key);if(state.mode!=='trial'&&!state.air&&!state.turnaround&&distance<8&&!observedInside.has(key)){observedInside.add(key);if(!progress.regions.includes(id))progress.regions.push(id);state.regions=[...progress.regions];state.v=state.vz=state.boost=0;previous=capturePose(state,area.ground(state.x,state.y));save();updateHud();showCard(p,null,'region');return;}}
 // Each ground-level entry opens the observation, including return visits.
 for(const i of detailIndices){const p=discoveries[i],distance=Math.hypot(state.x-p.x,state.y-p.y);if(distance>CLOSE_RANGE)observedInside.delete(i);if(!progress.regions.includes(regionIdForDetail(i)))continue;if(state.mode!=='trial'&&!state.air&&!state.turnaround&&distance<8&&!observedInside.has(i)){observedInside.add(i);if(!state.collected.includes(i))state.collected.push(i);progress.collected=[...state.collected];state.v=0;state.vz=0;state.boost=0;if(p.focus){state.heading=Math.atan2(p.focus.x-state.x,-(p.focus.y-state.y));gpu.camera={x:state.x,y:state.y,h:state.heading};gpu.bodySlope=null;}previous=capturePose(state,area.ground(state.x,state.y));save();updateHud();showDiscovery(i);break;}}
 if(nav.target&&Math.hypot(state.x-nav.target.x,state.y-nav.target.y)<=CLOSE_RANGE){nav.target=null;save();dirty=true;}
 if(state.mode==='trial'&&state.done)finishLap();
 if(!paused){const inside=Math.hypot(state.x-raceSite.x,state.y-raceSite.y)<raceSite.radius;if(!inside)entryArmed=true;entryTime=entryArmed?advanceEntry(entryTime,state,dt):0;if(entryTime>=raceSite.dwell)chooseRace();}
}

function frame(t){const dt=Math.min(.05,(t-last)/1000||0);last=t;if(ready){if(!paused){acc+=dt;while(acc>=1/60&&!paused){step(1/60);acc-=1/60;}if(t-lastDraw>=(quality==='performance'?32:0)){draw(Math.min(.05,(t-lastDraw)/1000));lastDraw=t;}if(t-lastSave>3000){save();lastSave=t;}}else if(dirty){draw(0);dirty=false;}
 if(t-lastHud>100){updateHud();lastHud=t;}if(t-lastMap>200){if(minimap.state.enabled)drawMap($('#mini-map'),true);if($('#map-dialog').open)drawMap();lastMap=t;}}
 requestAnimationFrame(frame);}
$('#discovery-continue').onclick=closeSheet;
$('#explore').onclick=explore;$('#race-again').onclick=chooseRace;$('#result-explore').onclick=explore;
$('#pause-button').onclick=()=>openDialog('#pause-dialog');$('#resume').onclick=()=>{closeDialogs();exploreOrResume();};
function exploreOrResume(){if(welcome)explore();else setPause(false);}
$('#end-lap').onclick=endLap;

for(const b of document.querySelectorAll('[data-close]'))b.onclick=closeSheet;
for(const d of document.querySelectorAll('dialog'))d.addEventListener('cancel',e=>{e.preventDefault();if(d.id==='photo-dialog')d.close();else if(d.id==='result-dialog')explore();else if(d.id==='jump-confirm-dialog')cancelJump();else closeSheet();});
async function roverMenu(){closeDialogs();setPause(true);try{await openCraft(selected,(id,chosenMods)=>{if(state.mode==='trial')endLap();Object.assign(mods,chosenMods??mods);selected=id;state.roverId=id;state.tune=explorationKit(id,mods);state.v=state.vz=state.boost=0;state.air=false;state.z=area.ground(state.x,state.y);previous=capturePose(state,state.z);gpu.reset(state);save();},{mods,jezero:true,compact:true,jumpAvailable:progress.regions.length>0||progress.collected.length>0,onTab:menuTab});}catch{openDialog('#pause-dialog');notify('Rover selection could not load. Try again.');}}
async function chooseRace(){entryTime=0;entryArmed=false;closeDialogs();setPause(true);try{await openCraft(selected,id=>{raceExplorer??=selected;selected=id;startLap();},{race:true,jezero:true,compact:true,onCancel:()=>{entryArmed=false;restoreExplorer();state.mode='free';state.tune=explorationKit(selected,mods);openDialog('#pause-dialog');}});}catch{openDialog('#pause-dialog');notify('Rover selection could not load. Try again.');}}
function menuTab(tab,caller=null){mapReturn=null;if(tab==='rover'){roverMenu();return;}const target={map:'#map-dialog',notes:'#notes-dialog',jump:'#jump-dialog',settings:'#pause-dialog'}[tab]??'#pause-dialog';openDialog(target,tab==='notes'?(caller==='#map-dialog'?'#map-dialog':'#pause-dialog'):null);}
function syncMenuTabs(){const available=progress.regions.length>0||progress.collected.length>0;for(const b of document.querySelectorAll('.menu-tabs [data-tab="jump"]')){b.disabled=!available;b.title=available?'':'Visit a location to unlock Jump To';}}
for(const tabs of document.querySelectorAll('.menu-tabs')){const current=tabs.closest('dialog').id;for(const [tab,label]of [['map','MAP'],['notes','FIELD NOTES'],['jump','JUMP TO'],['settings','SETTINGS'],['rover','ROVER']]){const b=document.createElement('button');b.textContent=label;b.dataset.tab=tab;if(tab==='notes')b.id=current==='pause-dialog'?'field-notes':current==='map-dialog'?'map-notes':'';if(tab==='rover'&&current==='pause-dialog')b.id='choose-craft';if(current===({map:'map-dialog',notes:'notes-dialog',jump:'jump-dialog',settings:'pause-dialog'})[tab])b.setAttribute('aria-current','page');b.onclick=()=>menuTab(tab,'#'+current);tabs.append(b);}}
function targetSite(p){nav.target=reachableTarget(p,area.bounds);nav.labels=true;save();dirty=true;openDialog('#map-dialog','#notes-dialog');notify(`Target set · ${p.name}`,3);}
function requestJump(p,returnTo='#jump-dialog'){pendingJump={p,returnTo};closeDialogs();setPause(true);$('#jump-confirm-title').textContent=`Jump to ${p.name}?`;$('#jump-confirm-copy').textContent='Leave your current position and jump to this visited site?';$('#jump-confirm-dialog').showModal();}
function cancelJump(){const returnTo=pendingJump?.returnTo;pendingJump=null;$('#jump-confirm-dialog').close();if(returnTo)openDialog(returnTo);else setPause(false);}
$('#jump-confirm-cancel').onclick=cancelJump;
$('#jump-confirm-go').onclick=()=>{const p=pendingJump?.p;if(!p)return;pendingJump=null;$('#jump-confirm-dialog').close();resetAt({...p,y:p.y-55,heading:Math.PI});explore();};
function renderJumpSites(){const list=$('#jump-sites');list.replaceChildren();const add=(p,prefix='')=>{const b=document.createElement('button');b.textContent=prefix+p.name;b.onclick=()=>requestJump(p);list.append(b);};for(const region of regions){const id=region.regionId??region.id;if(progress.regions.includes(id))add(region);}for(const i of detailIndices)if(progress.collected.includes(i))add(discoveries[i],'SITE · ');$('#jump-empty').hidden=!!list.children.length;syncMenuTabs();}
$('#view-controls').onclick=()=>{$('#controls-help').hidden=!$('#controls-help').hidden;};
$('#exit-rover').onclick=()=>{save();if(parent!==window)parent.postMessage({type:'astra-exit-rover'},location.origin);else location.href=new URL('../../../playtest/',import.meta.url).href;};
for(const b of document.querySelectorAll('[data-light]'))b.onclick=()=>{$('#light').value=b.dataset.light;$('#light').dispatchEvent(new Event('change'));};
$('#light').onchange=e=>{light=e.target.value;lighting();for(const b of document.querySelectorAll('[data-light]'))b.setAttribute('aria-pressed',String(b.dataset.light===light));dirty=true;save();};$('#quality').onchange=e=>{quality=e.target.value;dirty=true;save();};$('#storms-enabled').onchange=e=>{stormsEnabled=e.target.checked;if(!stormsEnabled){storm.age=-1;storm.haze=0;storm.wait=75;}dirty=true;save();};$('#map-enabled').onchange=e=>{minimap.state.enabled=e.target.checked;minimap.layout();dirty=true;save();};

$('#lamps').onclick=()=>{gpu.headlightsOverride=!(gpu.lampStrength>0);dirty=true;};
for(const id of ['left','right','drive','brake']){const b=$('#'+id);b.onpointerdown=e=>{if(paused)return;e.preventDefault();b.setPointerCapture(e.pointerId);pointers.set(e.pointerId,id);b.classList.add('active');sync();};const release=e=>{pointers.delete(e.pointerId);if(![...pointers.values()].includes(id))b.classList.remove('active');sync();};b.onpointerup=release;b.onpointercancel=release;b.onlostpointercapture=release;}
addEventListener('keydown',e=>{if(document.querySelector('dialog[open]')||!ready||e.target.closest('input,select,summary,a')||(e.target.closest('button')&&[' ','Enter'].includes(e.key))||(e.target===$('#lamps')&&[' ','Enter'].includes(e.key)))return;if(e.key==='Escape'){e.preventDefault();openDialog('#pause-dialog');return;}const k=e.key.toLowerCase();if(['w','a','s','d','arrowup','arrowdown','arrowleft','arrowright',' '].includes(k)){e.preventDefault();if(!paused){keys.add(k);sync();}}});addEventListener('keyup',e=>{keys.delete(e.key.toLowerCase());sync();});
addEventListener('blur',()=>{if(ready&&!paused)openDialog('#pause-dialog');});document.addEventListener('visibilitychange',()=>{if(document.hidden&&ready){if(!paused)openDialog('#pause-dialog');save();}});addEventListener('pagehide',save);addEventListener('resize',()=>{dirty=true;});
for(const event of ['contextmenu','selectstart'])$('.controls').addEventListener(event,e=>e.preventDefault());
try{
 area=await loadArea();readSave();gpu=new GPURenderer($('#world'),area);gpu.shadowMode='none';gpu.softSurfaceLighting=true;gpu.flightLighting=1;posts=gateGeometry();storm.southBoundary=area.bounds.maxY+1600;resetAt(progress.position??{...area.start,heading:-.4});for(const i of progress.collected)if(discoveries[i]&&Math.hypot(state.x-discoveries[i].x,state.y-discoveries[i].y)<CLOSE_RANGE)observedInside.add(i);for(const p of regions){const id=p.regionId??p.id;if(progress.regions.includes(id)&&Math.hypot(state.x-p.x,state.y-p.y)<CLOSE_RANGE)observedInside.add('region:'+id);}entryArmed=Math.hypot(state.x-raceSite.x,state.y-raceSite.y)>=raceSite.radius;ready=true;minimap.layout();$('#map-enabled').checked=minimap.state.enabled;$('#storms-enabled').checked=stormsEnabled;$('#quality').value=quality;$('#light').value=light;for(const b of document.querySelectorAll('[data-light]'))b.setAttribute('aria-pressed',String(b.dataset.light===light));$('#loading').hidden=true;
 if(progress.position||progress.collected.length||progress.regions.length){welcome=false;$('#welcome').hidden=true;openDialog('#pause-dialog');}
 $('#world').addEventListener('webglcontextlost',e=>{e.preventDefault();setPause(true);ready=false;$('#loading').hidden=false;$('#loading h2').textContent='The graphics paused.';$('#loading p').textContent='Your saved discoveries are safe.';const b=document.createElement('button');b.textContent='Reload terrain';b.onclick=()=>location.reload();$('#loading').append(b);});
 window.__jezero={get state(){return state},area,gpu,storm,progress,get worldUnlocked(){return worldUnlocked(progress,detailIndices,regions.map(r=>r.regionId??r.id))},get paused(){return paused},get input(){return input},landmarks,regions,nav,raceSite,get entryTime(){return entryTime},mods,minimap,get stormsEnabled(){return stormsEnabled},resetAt,step,draw,startLap,chooseRace,explore,setPause,save,openDialog,renderNotes,drawMap};requestAnimationFrame(frame);
}catch(e){console.error(e);$('#loading h2').textContent='Could not prepare Three Forks';$('#loading p').textContent=e.message;const b=document.createElement('button');b.textContent='Try again';b.onclick=()=>location.reload();$('#loading').append(b);}
