import {loadArea,toGame,toMars,UNITS} from './terrain.js';
import {readSave,writeSave,validPose} from './save.js';
import {GPURenderer} from '../mars-renderer/gpu.js';
import {create} from '../mars-renderer/simulation.js';
import {driveStep} from '../mars-renderer/driving.js';
import {explorationKit} from '../mars-renderer/kits.js';
import {capturePose,displayState} from '../mars-renderer/motion.js';
import {createRouteRibbon} from '../jezero/route-ribbon.js';
const $=s=>document.querySelector(s),keys=new Set(),pointers=new Map();
let area,gpu,state,previous,ready=false,paused=true,started=false,acc=0,last=0,lastDraw=0,lastUI=0,lastSave=0;
let routeOn=true,light='dusk',quality='balanced',target=null,visited=new Set(),lastGround=null,saveWarned=false,selected=0,mapZoom=1,mapCenter=null,reverseHeld=false;
const input={drive:false,brake:false,steer:0,reverse:false};
const relief=new Image();relief.src=new URL('./assets/relief.png',import.meta.url).href;relief.onload=()=>{if(ready)drawMap();};
function sync(){const held=new Set(pointers.values());input.drive=keys.has('w')||keys.has('arrowup')||held.has('drive');input.brake=keys.has(' ')||keys.has('s')||keys.has('arrowdown')||held.has('brake');input.reverse=keys.has('r')||reverseHeld;input.steer=(keys.has('d')||keys.has('arrowright')||held.has('right')?1:0)-(keys.has('a')||keys.has('arrowleft')||held.has('left')?1:0);}
function clearInput(){keys.clear();pointers.clear();reverseHeld=false;sync();document.querySelectorAll('.controls .active').forEach(b=>b.classList.remove('active'));}
function notify(text,seconds=4){if(!state)return;state.message=text;state.messageUntil=state.t+seconds;updateHUD();}
function save(){if(!ready)return;const pose=!state.air&&!state.turnaround&&validPose(state,area.bounds)?{x:state.x,y:state.y,heading:state.heading}:lastGround;if(!pose)return;lastGround=pose;let ok=false;try{ok=writeSave(localStorage,{position:pose,route:routeOn,light,quality,visited:[...visited],target:target?.id??null});}catch{}if(!ok&&!saveWarned){saveWarned=true;notify('Your browser could not save this outing.',8);}}
function lighting(){state.solar=light==='night'?{east:0,north:0,up:-1}:light==='dusk'?{east:-.68,north:.70,up:.22}:{east:-.45,north:.6,up:.66};$('#scene').style.background=light==='night'?'linear-gradient(#03060c,#080c14 65%,#151720)':light==='dusk'?'linear-gradient(#6a493c,#b88258 58%,#bc895f)':'linear-gradient(#75482f,#be8b62 53%,#b48059)';gpu.headlightsOverride=light==='night';$('#headlights').checked=light==='night';for(const b of document.querySelectorAll('[data-light]'))b.setAttribute('aria-pressed',String(b.dataset.light===light));}
function resetAt(p){state=create('free',area.course,'perseverance');Object.assign(state,{x:p.x,y:p.y,heading:p.heading??Math.PI,z:area.ground(p.x,p.y),tune:explorationKit('perseverance',{kit:true}),message:'',messageUntil:0});previous=capturePose(state,state.z);lastGround={x:state.x,y:state.y,heading:state.heading};gpu.reset(state);acc=0;clearInput();lighting();}
function setPause(value){paused=value;clearInput();acc=0;document.body.classList.toggle('paused',value);if(state)previous=capturePose(state,area.ground(state.x,state.y));if(value)save();draw(0);}
function openDialog(id){if(!ready)return;for(const d of document.querySelectorAll('dialog[open]'))d.close();setPause(true);$(id).showModal();if(id==='#map-dialog'){selectStop(selected);requestAnimationFrame(()=>drawMap());}}
function resume(){for(const d of document.querySelectorAll('dialog[open]'))d.close();started=true;$('#welcome').hidden=true;setPause(false);updateHUD();if(document.activeElement instanceof HTMLElement)document.activeElement.blur();}
function closestStop(){return area.stops.reduce((best,p)=>Math.hypot(p.x-state.x,p.y-state.y)<Math.hypot(best.x-state.x,best.y-state.y)?p:best);}
function travel(index){const p=area.stops[index];if(!p)return;resetAt(p);visited.add(p.id);target=null;selected=index;mapZoom=1;mapCenter=null;resume();notify(p.name+' · Curiosity sol '+p.sol);save();}
function step(dt){previous=capturePose(state,area.ground(state.x,state.y));const brake=input.brake||input.reverse;driveStep(state,{drive:input.drive,brake,brakeOnly:!input.reverse,steer:input.steer},dt,area.course,{...area.driveArea,rocks:area.localRocks(state.x,state.y)});
 // Only the outer envelope returns the rover. The recorded route has no gates.
 const b=area.bounds;if(state.x<b.minX-800||state.x>b.width+800||state.y<b.minY-800||state.y>b.maxY+800){state.x=Math.max(b.minX+120,Math.min(b.width-120,state.x));state.y=Math.max(b.minY+120,Math.min(b.maxY-120,state.y));state.z=area.ground(state.x,state.y);state.v=state.vz=0;state.air=state.turnaround=false;state.driftVX=state.driftVY=null;previous=capturePose(state,state.z);gpu.reset(state);notify('Back inside the exploration area.');}
 const p=closestStop();if(!state.air&&Math.hypot(p.x-state.x,p.y-state.y)<65&&!visited.has(p.id)){visited.add(p.id);notify(`Curiosity’s trail · sol ${p.sol}`);save();}
 if(target&&Math.hypot(target.x-state.x,target.y-state.y)<70){notify('You reached '+target.name.toLowerCase()+'.');target=null;save();}
}
function draw(dt){if(!ready)return;gpu.quality=quality;const shown=paused?state:displayState(previous,state,acc*60,area.ground(state.x,state.y));gpu.draw(shown,dt,$('#labels'));const ctx=$('#labels').getContext('2d');
 for(const p of area.stops){if(Math.hypot(p.x-shown.x,p.y-shown.y)>1000)continue;const z=area.ground(p.x,p.y)+12,q=gpu.project(p.x,p.y,z);if(q.depth<8||q.x<40||q.x>$('#labels').width-40||q.y<130||q.y>$('#labels').height-170)continue;const c=gpu.lastCamera;let blocked=false;for(let k=1;k<18;k++){const t=k/18;if(area.ground(c.x+(p.x-c.x)*t,c.y+(p.y-c.y)*t)>c.eye+(z-c.eye)*t){blocked=true;break;}}if(blocked)continue;ctx.font='12px system-ui';ctx.textAlign='center';ctx.fillStyle='#17282be8';ctx.fillRect(q.x-44,q.y-27,88,23);ctx.fillStyle='#ffe1a0';ctx.fillText('Sol '+p.sol,q.x,q.y-11);ctx.beginPath();ctx.arc(q.x,q.y,3,0,Math.PI*2);ctx.fill();}
}
function updateHUD(){if(!ready)return;const {north}=toMars(state.x,state.y);$('#place').textContent=north>-4000?'Landing basin':north>-10000?'Mount Sharp · lower slopes':'Mount Sharp · higher ground';$('#toast').textContent=state.boundary?'Edge of the open world · turn toward the basin':state.messageUntil>state.t?state.message:'';$('#speed').textContent=`${Math.round(Math.abs(state.v)/4*3.6)} km/h · ASTRA rover`;$('#brake').textContent=state.air?'Slow':reverseHeld?'Reverse':Math.abs(state.v)<.5&&!input.brake?'Reverse':'Brake';const e=$('#target-hud');e.hidden=!target;if(target){const angle=Math.atan2(target.x-state.x,-(target.y-state.y))-state.heading,d=Math.hypot(target.x-state.x,target.y-state.y)/4;e.textContent=`${Math.abs(Math.atan2(Math.sin(angle),Math.cos(angle)))<.25?'↑':Math.sin(angle)>0?'→':'←'} ${target.name} · ${d>=1000?(d/1000).toFixed(1)+' km':Math.round(d)+' m'}`;}}
function frame(t){const dt=Math.min(.05,(t-last)/1000||0);last=t;if(ready){if(!paused&&!document.hidden){acc+=dt;while(acc>=1/60){step(1/60);acc-=1/60;}if(t-lastDraw>=(quality==='performance'?32:0)){draw(Math.min(.05,(t-lastDraw)/1000));lastDraw=t;}if(t-lastSave>3000){save();lastSave=t;}}if(t-lastUI>180){updateHUD();drawMap($('#mini'),true);if($('#map-dialog').open)drawMap();lastUI=t;}}requestAnimationFrame(frame);}
function mapFrame(c,mini){const rect=c.getBoundingClientRect(),w=rect.width,h=rect.height,dpr=Math.min(devicePixelRatio,2);if(!w||!h)return null;if(c.width!==Math.round(w*dpr)||c.height!==Math.round(h*dpr)){c.width=Math.round(w*dpr);c.height=Math.round(h*dpr);}const ctx=c.getContext('2d');ctx.setTransform(dpr,0,0,dpr,0,0);const b=area.bounds,center=mini?{x:state.x,y:state.y}:mapCenter??{x:(b.minX+b.width)/2,y:(b.minY+b.maxY)/2},scale=mini?Math.min(w,h)/3400:Math.min(w/(b.width-b.minX),h/(b.maxY-b.minY))*.9*mapZoom;return {ctx,w,h,scale,center,point:p=>({x:w/2+(p.x-center.x)*scale,y:h/2+(p.y-center.y)*scale})};}
function drawMap(canvas=$('#map'),mini=false){if(!ready)return;const f=mapFrame(canvas,mini);if(!f)return;const {ctx,w,h,scale,point}=f;ctx.clearRect(0,0,w,h);ctx.fillStyle='#342d25';ctx.fillRect(0,0,w,h);const [west,east,south,north]=area.info.context.bounds,a=point(toGame(west,north));if(relief.complete&&relief.naturalWidth)ctx.drawImage(relief,a.x,a.y,(east-west)*UNITS*scale,(north-south)*UNITS*scale);
 const b=area.bounds,tl=point({x:b.minX,y:b.minY});ctx.fillStyle='#91dfb40b';ctx.fillRect(tl.x,tl.y,(b.width-b.minX)*scale,(b.maxY-b.minY)*scale);ctx.strokeStyle='#b8f5d6';ctx.lineWidth=1.2;ctx.setLineDash([5,4]);ctx.strokeRect(tl.x,tl.y,(b.width-b.minX)*scale,(b.maxY-b.minY)*scale);ctx.setLineDash([]);
 ctx.strokeStyle='#ffe099';ctx.lineWidth=mini?1.5:1.7;ctx.beginPath();for(const segment of area.segments){let first=true;for(const p of segment.points){const q=point(p);if(first){ctx.moveTo(q.x,q.y);first=false;}else ctx.lineTo(q.x,q.y);}}ctx.stroke();
 if(!mini)for(let i=0;i<area.stops.length;i++){const p=area.stops[i],q=point(p);ctx.beginPath();ctx.arc(q.x,q.y,i===selected?10:8,0,Math.PI*2);ctx.fillStyle=i===selected?'#ffdf89':visited.has(p.id)?'#a4d6b8':'#1b3034';ctx.fill();ctx.strokeStyle='#e6e4ce';ctx.stroke();ctx.font='10px system-ui';ctx.textAlign='center';ctx.fillStyle=i===selected||visited.has(p.id)?'#17282b':'#fff';ctx.fillText(i+1,q.x,q.y+3);}
 if(target){const q=point(target);ctx.strokeStyle='#bfffdf';ctx.lineWidth=2;ctx.beginPath();ctx.arc(q.x,q.y,14,0,Math.PI*2);ctx.stroke();}
 const q=point(state);ctx.save();ctx.translate(q.x,q.y);ctx.rotate(state.heading);ctx.beginPath();ctx.moveTo(0,-8);ctx.lineTo(5,6);ctx.lineTo(0,3);ctx.lineTo(-5,6);ctx.closePath();ctx.fillStyle='#fff';ctx.strokeStyle='#142b30';ctx.lineWidth=2;ctx.stroke();ctx.fill();ctx.restore();
 ctx.font='11px system-ui';ctx.textAlign='left';ctx.fillStyle='#fff';ctx.fillText('N ↑',10,18);if(!mini){const length=4000;ctx.fillStyle='#17282bdd';ctx.fillRect(8,h-38,Math.max(140,length*scale+20),31);ctx.strokeStyle='#fff';ctx.beginPath();ctx.moveTo(16,h-27);ctx.lineTo(16+length*scale,h-27);ctx.stroke();ctx.fillStyle='#fff';ctx.fillText('1 game km · 1.5 km Mars',16,h-13);}}
function selectStop(i){selected=Math.max(0,Math.min(area.stops.length-1,i));const p=area.stops[selected];$('#destination').value=String(selected);$('#destination-copy').textContent=`Sol ${p.sol} · ${p.name}. NASA records ${(p.odometer/1000).toFixed(2)} km travelled and ${Math.round(p.elevation-area.stops[0].elevation)} m of elevation gain from the first waypoint.`;$('#clear-target').hidden=!target;drawMap();}
for(const b of document.querySelectorAll('[data-control]')){b.addEventListener('pointerdown',e=>{e.preventDefault();if(paused)return;b.setPointerCapture(e.pointerId);if(b.dataset.control==='brake'&&Math.abs(state.v)<.5&&!state.air)reverseHeld=true;pointers.set(e.pointerId,b.dataset.control);b.classList.add('active');sync();});const up=e=>{pointers.delete(e.pointerId);if(b.dataset.control==='brake')reverseHeld=false;b.classList.remove('active');sync();};b.addEventListener('pointerup',up);b.addEventListener('pointercancel',up);b.addEventListener('lostpointercapture',up);}
window.addEventListener('keydown',e=>{if(!ready)return;const k=e.key.toLowerCase();if(['input','select','textarea'].includes(document.activeElement?.tagName.toLowerCase()))return;if(k==='escape'){e.preventDefault();if(document.querySelector('dialog[open]'))resume();else if(started)openDialog('#settings');return;}if(k==='m'&&!e.repeat){e.preventDefault();if($('#map-dialog').open)resume();else openDialog('#map-dialog');return;}if(paused)return;if(e.repeat&&!keys.has(k))return;if(['w','a','s','d','r',' ','arrowup','arrowdown','arrowleft','arrowright'].includes(k)){e.preventDefault();keys.add(k);sync();}});
window.addEventListener('keyup',e=>{keys.delete(e.key.toLowerCase());sync();});window.addEventListener('blur',()=>{if(ready&&!paused)openDialog('#settings');else clearInput();});document.addEventListener('visibilitychange',()=>{if(document.hidden&&ready&&!paused)openDialog('#settings');});window.addEventListener('pagehide',save);window.addEventListener('astra-close-practice',()=>{if(ready)setPause(true);});
for(const d of document.querySelectorAll('dialog'))d.addEventListener('cancel',e=>{e.preventDefault();resume();});for(const b of document.querySelectorAll('[data-close]'))b.onclick=resume;
$('#begin').onclick=resume;$('#resume').onclick=resume;$('#pause').onclick=()=>openDialog('#settings');for(const id of ['mini-button','open-map','welcome-map'])$('#'+id).onclick=()=>openDialog('#map-dialog');$('#retry').onclick=()=>location.reload();$('#recover').onclick=()=>travel(area.stops.indexOf(closestStop()));$('#exit').onclick=()=>{save();if(parent!==window)parent.postMessage({type:'astra-exit-rover'},location.origin);else location.href=new URL('../../../playtest/',location.href).href;};
$('#route-enabled').onchange=e=>{routeOn=e.target.checked;gpu.routeRibbon=routeOn?gpu.galeRibbon:null;save();draw(0);};$('#quality').onchange=e=>{quality=e.target.value;save();draw(0);};for(const b of document.querySelectorAll('[data-light]'))b.onclick=()=>{light=b.dataset.light;lighting();save();draw(0);};$('#headlights').onchange=e=>{gpu.headlightsOverride=e.target.checked;draw(0);};$('#destination').onchange=e=>selectStop(Number(e.target.value));$('#travel').onclick=()=>travel(selected);$('#guide').onclick=()=>{target=area.stops[selected];resume();save();};$('#clear-target').onclick=()=>{target=null;save();selectStop(selected);};
$('#zoom-in').onclick=()=>{mapZoom=Math.min(5,mapZoom*1.5);mapCenter=area.stops[selected];drawMap();};$('#zoom-out').onclick=()=>{mapZoom=Math.max(1,mapZoom/1.5);if(mapZoom===1)mapCenter=null;drawMap();};$('#zoom-reset').onclick=()=>{mapZoom=1;mapCenter=null;drawMap();};$('#map').onclick=e=>{const f=mapFrame($('#map'),false),r=$('#map').getBoundingClientRect();let best=-1,distance=28;area.stops.forEach((p,i)=>{const q=f.point(p),d=Math.hypot(q.x-e.clientX+r.left,q.y-e.clientY+r.top);if(d<distance){best=i;distance=d;}});if(best>=0)selectStop(best);};
window.addEventListener('resize',()=>{if(ready){draw(0);drawMap();drawMap($('#mini'),true);}});$('#world').addEventListener('webglcontextlost',e=>{e.preventDefault();if(ready)setPause(true);$('#loading').hidden=false;$('#loading-copy').textContent='Graphics paused. Reload to continue from your saved position.';$('#retry').hidden=false;});
async function boot(){try{area=await loadArea();$('#loading-copy').textContent='Preparing the rover and mountain views…';await new Promise(r=>requestAnimationFrame(r));gpu=new GPURenderer($('#world'),area);gpu.shadowMode='none';gpu.softSurfaceLighting=true;gpu.flightLighting=1;gpu.galeRibbon=createRouteRibbon(gpu,area.segments,area.ground,{halfWidth:1.4,color:[.95,.76,.43],emissive:true});let stored=null;try{stored=readSave(localStorage,area.bounds);}catch{}if(stored){routeOn=stored.route;light=stored.light;quality=stored.quality;visited=new Set(stored.visited.filter(id=>area.stops.some(p=>p.id===id)));target=area.stops.find(p=>p.id===stored.target)??null;}gpu.routeRibbon=routeOn?gpu.galeRibbon:null;resetAt(stored?.position??area.start);$('#route-enabled').checked=routeOn;$('#quality').value=quality;$('#destination').replaceChildren(...area.stops.map((p,i)=>{const o=document.createElement('option');o.value=i;o.textContent=`${i+1}. ${p.name} · Sol ${p.sol}`;return o;}));ready=true;document.body.classList.add('paused');$('#loading').hidden=true;$('#welcome').hidden=false;$('#begin').textContent=stored?'Continue exploring':'Explore Gale';selectStop(0);draw(0);updateHUD();requestAnimationFrame(frame);
 window.__gale={get state(){return state;},get paused(){return paused;},get area(){return area;},get gpu(){return gpu;},get visited(){return [...visited];},get input(){return {...input};},travel,save,step,draw,resume,openMap:()=>openDialog('#map-dialog')};
 }catch(e){console.error(e);$('#loading-copy').textContent=e.message||'Gale could not load. Reload to try again.';$('#retry').hidden=false;}}
boot();
