import {CRAFT} from './craft-data.js';
import {kit} from './kits.js';
let dialog,viewer,index=0,choose,restore,ready,loadTimer;
function fitModel(){if(!viewer?.loaded||!dialog.open)return;const c=viewer.getBoundingBoxCenter(),d=viewer.getDimensions(),radius=Math.hypot(d.x,d.y,d.z)*.56/Math.sin(Math.PI/12)/Math.min(1,viewer.clientWidth/Math.max(1,viewer.clientHeight));viewer.cameraTarget=`${c.x}m ${c.y}m ${c.z}m`;viewer.cameraOrbit=`35deg 68deg ${radius}m`;viewer.fieldOfView='30deg';viewer.jumpCameraToGoal();}
function refresh(retryQuery=''){const c=CRAFT[index],k=kit(c.id);dialog.querySelector('h1').textContent=c.name;dialog.querySelector('.meta').textContent=`${c.site} · ${c.dates}`;dialog.querySelector('#craft-copy').textContent=c.about;dialog.querySelector('.craft-credit').textContent=c.credit;dialog.querySelector('#craft-extra').hidden=true;
 dialog.querySelector('#craft-extra').innerHTML=`<p>${c.discovery}</p><p>${c.power} · Mass ${c.mass}</p><p>Drag to rotate; pinch or scroll to zoom. Driving uses a lightweight version of this rover. Steering is shared; real mass is reference information.</p><a href="${c.source}" target="_blank" rel="noopener noreferrer">NASA mission ↗</a>`;
 dialog.querySelector('.craft-stats').innerHTML=[['Handling','Shared'],['Acceleration',`${k.acceleration} u/s²`],['Top speed',`${k.speed} u/s`],['Boost','1.5× · 1.5 s'],['Real mass',c.mass]].map(([a,b])=>`<div><dt>${a}</dt><dd>${b}</dd></div>`).join('');
 for(const b of dialog.querySelectorAll('[data-craft]'))b.setAttribute('aria-pressed',String(b.dataset.craft===c.id));
 clearTimeout(loadTimer);const fallback=dialog.querySelector('#craft-fallback');fallback.hidden=false;fallback.src=new URL(`./assets/${c.id==='opportunity'?'spirit':c.id}-preview.webp`,import.meta.url).href;fallback.alt=`${c.name} image preview`;dialog.querySelector('#craft-retry').hidden=true;dialog.querySelector('#craft-status').textContent='Loading 3D…';loadTimer=setTimeout(()=>{if(!fallback.hidden){dialog.querySelector('#craft-status').textContent='Image preview';dialog.querySelector('#craft-retry').hidden=false;}},8000);viewer.poster=new URL(`./assets/${c.id==='opportunity'?'spirit':c.id}-preview.webp`,import.meta.url).href;viewer.alt=`${c.name} rover model`;const url=new URL(`./assets/${c.model}${retryQuery}`,import.meta.url).href;if(viewer.src===url&&viewer.loaded){dialog.querySelector('#craft-status').textContent='';fallback.hidden=true;clearTimeout(loadTimer);}else viewer.src=url;viewer.cameraOrbit='35deg 68deg auto';viewer.fieldOfView='30deg';requestAnimationFrame(()=>requestAnimationFrame(fitModel));
}
function close(){clearTimeout(loadTimer);dialog.close();viewer.removeAttribute('src');restore?.focus();}
async function setup(){window.ModelViewerElement={dracoDecoderLocation:new URL('./vendor/draco/',import.meta.url).href};await import('./vendor/model-viewer.min.js');customElements.get('model-viewer').dracoDecoderLocation=new URL('./vendor/draco/',import.meta.url).href;customElements.get('model-viewer').modelCacheSize=1;
 const css=document.createElement('link');css.rel='stylesheet';css.href=new URL('./craft.css',import.meta.url);document.head.append(css);
 dialog=document.createElement('dialog');dialog.id='craft-dialog';dialog.setAttribute('aria-label','Choose craft');dialog.innerHTML=`<header><strong>Choose craft</strong><button id="craft-info" aria-label="Rover information">i</button><button id="craft-close" aria-label="Close craft selection">×</button></header><div class="craft-body"><div class="craft-stage"><model-viewer loading="eager" reveal="auto" camera-controls touch-action="none" interaction-prompt="none" exposure="1.2" shadow-intensity="0.6" camera-orbit="35deg 68deg auto" min-camera-orbit="auto 15deg auto" max-camera-orbit="auto 90deg auto"></model-viewer><img id="craft-fallback" alt="Rover preview"><button id="craft-retry" hidden>Retry 3D</button><span id="craft-status" role="status"></span><div class="craft-arrows"><button id="craft-prev" aria-label="Previous rover">‹</button><button id="craft-next" aria-label="Next rover">›</button></div><span class="craft-credit"></span><div class="craft-zoom"><button id="craft-reset" aria-label="Reset rover view">↺</button><button id="craft-minus" aria-label="Zoom out">−</button><button id="craft-plus" aria-label="Zoom in">+</button></div></div><section class="craft-details"><h1></h1><div class="meta"></div><p id="craft-copy"></p><h2>ASTRA driving kit</h2><dl class="craft-stats"></dl><small>Fictional upgrades · u = game units.</small><div id="craft-extra" hidden></div></section></div><footer class="craft-bottom"><nav class="craft-carousel" aria-label="Rovers">${CRAFT.map(c=>`<button data-craft="${c.id}" aria-pressed="false"><img alt="" src="${new URL(`./assets/${c.id==='opportunity'?'spirit':c.id}-preview.webp`,import.meta.url).href}"><span>${c.name}</span></button>`).join('')}</nav><div class="craft-actions"><span></span><button id="craft-use">Use craft</button></div></footer>`;document.body.append(dialog);viewer=dialog.querySelector('model-viewer');
 viewer.addEventListener('load',()=>{clearTimeout(loadTimer);dialog.querySelector('#craft-fallback').hidden=true;dialog.querySelector('#craft-retry').hidden=true;viewer.dismissPoster();dialog.querySelector('#craft-status').textContent='';requestAnimationFrame(()=>requestAnimationFrame(fitModel));});viewer.addEventListener('error',()=>{clearTimeout(loadTimer);dialog.querySelector('#craft-fallback').hidden=false;dialog.querySelector('#craft-retry').hidden=false;dialog.querySelector('#craft-status').textContent='Image preview';});dialog.querySelector('#craft-retry').onclick=async()=>{viewer.removeAttribute('src');await viewer.updateComplete;requestAnimationFrame(()=>refresh(`?retry=${Date.now()}`));};
 new ResizeObserver(()=>requestAnimationFrame(fitModel)).observe(viewer);dialog.querySelector('#craft-reset').onclick=fitModel;dialog.querySelector('#craft-close').onclick=close;dialog.addEventListener('cancel',e=>{e.preventDefault();close();});
 dialog.querySelector('#craft-prev').onclick=()=>{index=(index+CRAFT.length-1)%CRAFT.length;refresh();};dialog.querySelector('#craft-next').onclick=()=>{index=(index+1)%CRAFT.length;refresh();};
 dialog.querySelector('#craft-info').onclick=()=>{const e=dialog.querySelector('#craft-extra');e.hidden=!e.hidden;if(!e.hidden)e.scrollIntoView({block:'nearest',behavior:'smooth'});};
 for(const b of dialog.querySelectorAll('[data-craft]'))b.onclick=()=>{index=CRAFT.findIndex(c=>c.id===b.dataset.craft);refresh();};
 for(const [id,factor]of [['craft-minus',1.15],['craft-plus',.87]])dialog.querySelector('#'+id).onclick=()=>{const o=viewer.getCameraOrbit();viewer.cameraOrbit=`${o.theta}rad ${o.phi}rad ${Math.max(.05,o.radius*factor)}m`;};
 dialog.querySelector('#craft-use').onclick=()=>{choose(CRAFT[index].id);close();};
}
export async function openCraft(selected,onChoose){restore=document.activeElement;choose=onChoose;ready??=setup();await ready;index=Math.max(0,CRAFT.findIndex(c=>c.id===selected));dialog.showModal();refresh();dialog.querySelector('#craft-close').focus();}
