import {toGame} from './terrain.js';
import {landingPhoto,seitahPhoto} from './tour-photos.js';

// Keep locator maps available alongside approved rover photographs.
const relief={image:'./assets/floor-relief.webp',imageAlt:'North-up topographic map of the landing plain and Séítah',imageDescription:'Topographic map, not a rover photograph. Relief derived from the USGS Mars 2020 HiRISE elevation mosaic; north is up. Shading describes relief, not surface color.',imageCredit:'USGS / NASA / JPL-Caltech / University of Arizona · ASTRA relief map',imageType:'map',source:'https://astrogeology.usgs.gov/search/map/mars-2020-jezero-crater-landing-site-products'};
const landingMap={image:'./assets/landing.jpg',imageAlt:'Orbital locator map of Octavia E. Butler Landing',imageDescription:'Orbital locator map, not a ground photograph. The actual touchdown reference is on the landing plain.',imageCredit:'NASA/JPL-Caltech/University of Arizona · PIA24483',imageType:'map',source:'https://science.nasa.gov/resource/welcome-to-octavia-e-butler-landing/'};
const at=(id,name,e,n,copy)=>({id,name,...toGame(e,n),...copy});
export const floorRegions=[
 at('landing-plain','Landing plain',2200,-820,{...landingMap,kind:'region',fact:'Perseverance landed on Jezero’s crater floor on 18 February 2021. Before exploring the delta, it investigated the rocks and sands of this broad plain.',detail:'Find the landing marker revealed on your map. It marks the mission’s real touchdown reference; the history stop back at Three Forks tells the story from a different location.',source:'https://science.nasa.gov/resource/welcome-to-octavia-e-butler-landing/',positionEvidence:'Authored regional overview on the measured crater floor; not the touchdown position.'}),
 at('seitah','Séítah',1800,-1370,{...relief,kind:'region',fact:'Séítah is a landscape of exposed rock amongst sand. Its rocks helped reveal that parts of Jezero’s crater floor formed from cooling magma.',detail:'Choose your way through open sand and scattered rock exposures. The rocks here tell a different story from the sedimentary layers of the delta. Local boulders are representative scenery, not individually surveyed mission targets.',source:'https://science.nasa.gov/blog/perseverance-and-the-search-amongst-the-sand/',positionEvidence:'Authored overview northwest of the pinned sol-201 camera-area reference, not a surveyed formation boundary.'}),
];
export const floorDiscoveries=[
 at('touchdown','Octavia E. Butler Landing',2579.896483,-970.495731,{...landingMap,kind:'history',fact:'This is where Perseverance’s surface journey began. NASA named the landing site for science-fiction author Octavia E. Butler.',detail:'The marker uses NASA’s recorded rover reference 3_0, sol 13, described as no motion. It is distinct from the reachable landing-history orb at Three Forks. The game’s rover is your explorer; there is no second Perseverance waiting here.',source:'https://science.nasa.gov/resource/welcome-to-octavia-e-butler-landing/',featurePosition:{longitude:77.45088572,latitude:18.44462715},cameraReference:'3_0',positionEvidence:'Pinned NASA waypoint 3_0, sol 13, no motion; mission-map precision, not a new survey.'}),
 at('seitah-crystals','Crystals from magma',2040.213210,-1677.355983,{...relief,kind:'site',fact:'Séítah’s rocks contain abundant olivine crystals. Their textures and chemistry point to an igneous origin: rock formed as molten material cooled.',detail:'Water later altered some minerals, but water alteration is not the same thing as deposition on a lake bed. Comparing these rocks with the delta teaches two different chapters of Jezero’s history. This stop uses a known rover camera-area reference; nearby game rocks are representative, not replicas of the analyzed outcrops.',source:'https://ntrs.nasa.gov/citations/20220012767',cameraReference:'7_1358',positionEvidence:'Pinned sol-201 camera-area waypoint; not the location of a specific analyzed crystal or sample.'}),
];
Object.assign(floorDiscoveries.find(p=>p.id==='touchdown'),landingPhoto,{views:[landingMap]});
Object.assign(floorRegions.find(p=>p.id==='landing-plain'),landingPhoto,{views:[landingMap],locationNote:'Regional overview; photograph recorded at the landing site.'});
Object.assign(floorRegions.find(p=>p.id==='seitah'),seitahPhoto,{views:[relief],locationNote:'Regional overview; photograph recorded at the sol-180 rover reference.'});
