/** Shared instructions for the current Moon/Gale gesture parser. */
export function rideHelp(vehicle='scooter'){
 const ski=vehicle==='ski';
 return `<p><b>Move:</b> Thrust: Space. Steer: A / D or ← / →. Special / Trick: Shift.</p>
 ${ski?'<p><b>Downhill:</b> Gravity follows the slope, including sideways. Left/right carve and shed speed; release to keep your chosen heading. Gate flags show the slalom line without pulling you onto it. Hold both arrows to brake in slalom. Release Thrust and carve to shed speed. Space boosts through wider powered turns. Special is reserved for tricks.</p>':''}
 <p><b>Hop / descend:</b> Double-tap Thrust for a strong ground hop or an airborne slam. A released pair gives a strong downward burst; hold the second press to sustain it. Hold Thrust with left/right to redirect your flight, even during tricks. A held slam takes priority over turning.</p>
 <p><b>Trick trees:</b> Left + 1 / 2 / 3 Trick taps: ${ski?'blade tuck / one-blade tuck / barrel roll':'board grab / one-handed grab / barrel roll'}. Left–Right + 1 / 2 / 3 taps: ${ski?'rover extension / blade stand / front flip':'Superman / bar headstand / front flip'}. Right-first mirrors each tree. Repeating the same direction does not select another trick. Each extra Trick tap must arrive within 0.32 seconds of the previous one. Tap for a full motion; hold the last press to sustain a pose or repeat rotations. Release before landing. Direction history lasts one second; it never steers the vehicle after release. LRLR + double Trick: ${ski?'Red Planet Rodeo, a scripted triple corkscrew':'The 9000, fifty full rider-and-scooter spins'}.</p>
 ${ski?'<p>Clean landings bank the combo. Held grabs and unfinished tricks lose it. No Manual on skis.</p>':`<details><summary>Manual &amp; combos</summary><p>While moving on the ground, double-tap Special with all other controls released. In the air, the same gesture arms a landing Manual only when too low to start a trick. It must be your last input before landing; it cannot arm during a trick.</p><p>Left/right balance. Hold Thrust to steer instead; release Thrust to balance again. Stopping keeps the Manual but makes balancing harder. Any airtime ends the Manual and keeps the combo alive. Double-tap Special again to arm the next Manual. Double-tap Special while manualing to cancel and bank it. A double-tap Thrust hop ends the Manual; it never resumes automatically.</p><p>Free roam and the two-minute run share controls. Clean landings bank the combo; unfinished tricks and lost balance lose it. Collect M-O-O-N for a bonus. At 0:00, finish your active combo.</p></details>`}`;
}
