export function createViewModes(api){
 const {gpu}=api,$=s=>document.querySelector(s);let overhead=false,photo=false,pose=null,priorCamera=null;const keys=new Set();
 const toggle=document.createElement('button');toggle.id='overhead-mode';toggle.textContent='⌖';toggle.title='Overhead drawing view (O)';toggle.setAttribute('aria-label','Overhead drawing view');toggle.setAttribute('aria-pressed','false');$('header nav').prepend(toggle);
 const panel=document.createElement('section');panel.id='free-camera';panel.hidden=true;panel.innerHTML='<div class="camera-top"><b>CAMERA</b><button id="camera-close">Back to pause</button></div><div class="camera-actions"><button data-camera="forward">Forward</button><button data-camera="back">Back</button><button data-camera="left">Left</button><button data-camera="right">Right</button><button data-camera="up">Rise</button><button data-camera="down">Lower</button><button id="camera-home">Frame rover</button><button id="camera-shot">Save image</button><label>Lens <input id="camera-lens" type="range" min="0.5" max="2.5" step="0.05" value="1"></label><label>Speed <input id="camera-speed" type="range" min="20" max="600" step="10" value="120"></label></div><small>Drag to look · WASD move · Q/E lower/rise · wheel changes lens · Escape returns to pause</small>';document.body.append(panel);
 const button=document.createElement('button');button.id='enter-camera';button.textContent='Camera mode';$('#pause-dialog .settings-stack').insertBefore(button,$('#resume').nextSibling);
 function frameRover(){const s=api.state;pose={x:s.x-Math.sin(s.heading)*85,y:s.y+Math.cos(s.heading)*85,eye:s.z+35,heading:s.heading,pitch:.25,zoom:1,live:true,free:true};$('#camera-lens').value='1';}
 function close(){if(!photo)return;photo=false;keys.clear();panel.hidden=true;document.body.classList.remove('free-camera-active');gpu.photoView=null;gpu.camera=priorCamera;api.openPause();}
 button.onclick=()=>{api.pause();api.closeDialogs();priorCamera={...gpu.camera};photo=true;frameRover();panel.hidden=false;document.body.classList.add('free-camera-active');api.redraw();};$('#camera-close').onclick=close;$('#camera-home').onclick=frameRover;
 toggle.onclick=()=>{overhead=!overhead;toggle.setAttribute('aria-pressed',String(overhead));gpu.photoView=null;gpu.camera={x:api.state.x,y:api.state.y,h:api.state.heading};api.redraw();};
 $('#camera-lens').oninput=e=>{if(pose)pose.zoom=Number(e.target.value);};
 for(const b of panel.querySelectorAll('[data-camera]')){b.onpointerdown=e=>{e.preventDefault();b.setPointerCapture(e.pointerId);keys.add(b.dataset.camera);};for(const event of ['pointerup','pointercancel','lostpointercapture'])b.addEventListener(event,()=>keys.delete(b.dataset.camera));}
 let drag=null;$('#world').addEventListener('pointerdown',e=>{if(!photo)return;drag={x:e.clientX,y:e.clientY};e.target.setPointerCapture(e.pointerId);});$('#world').addEventListener('pointermove',e=>{if(!photo||!drag)return;pose.heading+=(e.clientX-drag.x)*.006;pose.pitch=Math.max(-1.4,Math.min(1.55,pose.pitch+(e.clientY-drag.y)*.006));drag={x:e.clientX,y:e.clientY};});for(const ev of ['pointerup','pointercancel','lostpointercapture'])$('#world').addEventListener(ev,()=>drag=null);
 $('#world').addEventListener('wheel',e=>{if(!photo)return;e.preventDefault();pose.zoom=Math.max(.5,Math.min(2.5,pose.zoom*Math.exp(-e.deltaY*.001)));$('#camera-lens').value=String(pose.zoom);},{passive:false});
 const map={w:'forward',s:'back',a:'left',d:'right',q:'down',e:'up',arrowup:'forward',arrowdown:'back',arrowleft:'left',arrowright:'right'};
 addEventListener('keydown',e=>{if(photo){if(e.key==='Escape'){e.preventDefault();e.stopImmediatePropagation();close();return;}if(map[e.key.toLowerCase()]){keys.add(map[e.key.toLowerCase()]);e.preventDefault();e.stopImmediatePropagation();}}else if(e.key.toLowerCase()==='o'&&!e.repeat&&!document.querySelector('dialog[open]'))toggle.click();},true);addEventListener('keyup',e=>keys.delete(map[e.key.toLowerCase()]));addEventListener('blur',()=>keys.clear());
 $('#camera-shot').onclick=()=>{api.redraw();requestAnimationFrame(()=>{api.redraw();const a=document.createElement('a');a.download='LANDER-Jezero.png';const out=document.createElement('canvas');out.width=gpu.canvas.width;out.height=gpu.canvas.height;const ctx=out.getContext('2d'),gradient=ctx.createLinearGradient(0,0,0,out.height),night=(api.state.solar?.up??1)<0;gradient.addColorStop(0,night?'#03060c':'#75482f');gradient.addColorStop(1,night?'#151720':'#b48059');ctx.fillStyle=gradient;ctx.fillRect(0,0,out.width,out.height);ctx.drawImage($('#night-sky'),0,0,out.width,out.height);ctx.drawImage(gpu.canvas,0,0);a.href=out.toDataURL('image/png');a.click();});};
 return {get overhead(){return overhead},get photo(){return photo},close,tick(dt){if(!photo)return;const speed=Number($('#camera-speed').value)*dt,f=Number(keys.has('forward'))-Number(keys.has('back')),r=Number(keys.has('right'))-Number(keys.has('left'));pose.x+=(Math.sin(pose.heading)*f+Math.cos(pose.heading)*r)*speed;pose.y+=(-Math.cos(pose.heading)*f+Math.sin(pose.heading)*r)*speed;pose.eye+=(Number(keys.has('up'))-Number(keys.has('down')))*speed;pose.eye=Math.max(api.area.ground(pose.x,pose.y)+3,pose.eye);gpu.photoView=pose;api.redraw();},draw(shown,dt,overlay){
  if(photo){gpu.photoView=pose;gpu.draw(shown,0,overlay);return true;}
  if(!overhead)return false;
  const camera={...gpu.camera};gpu.photoView=null;gpu.draw(shown,dt,overlay);const mini=$('#mini-map'),ctx=mini.getContext('2d');mini.width=Math.max(1,mini.clientWidth*devicePixelRatio);mini.height=Math.max(1,mini.clientHeight*devicePixelRatio);const cw=gpu.canvas.width*.45,ch=gpu.canvas.height*.7;ctx.drawImage(gpu.canvas,(gpu.canvas.width-cw)/2,gpu.canvas.height*.2,cw,ch,0,0,mini.width,mini.height);gpu.camera=camera;gpu.photoView={x:shown.x,y:shown.y,heading:0,pitch:Math.PI/2,extent:65,live:true};gpu.draw(shown,0,overlay);return true;
 }};
}
