// Render the actual terrain/scenery from the lamp. No height-field ray steps.
export class HeadlightShadow {
 constructor(gl){this.gl=gl;this.size=1024;const compile=(type,source)=>{const s=gl.createShader(type);gl.shaderSource(s,source);gl.compileShader(s);if(!gl.getShaderParameter(s,gl.COMPILE_STATUS))throw Error(gl.getShaderInfoLog(s));return s;};
 const vs=`attribute vec3 position;uniform vec3 origin;uniform float groundDrop;uniform vec2 heading,tilt;varying float depth;void main(){vec3 d=position-vec3(0.,0.,groundDrop)-origin;float f=dot(d.xy,heading),r=dot(d.xy,vec2(-heading.y,heading.x));depth=f*tilt.x+d.z*tilt.y;float u=d.z*tilt.x-f*tilt.y;gl_Position=vec4(r/1.8,u/1.6,1.00501253*depth-10.0250627,depth);}`;
 const fs=`precision highp float;varying float depth;void main(){float v=clamp(depth/2000.,0.,.999999);vec3 e=fract(v*vec3(1.,255.,65025.));e-=e.yzz*vec3(1./255.,1./255.,0.);gl_FragColor=vec4(e,1.);}`;
 this.program=gl.createProgram();gl.attachShader(this.program,compile(gl.VERTEX_SHADER,vs));gl.attachShader(this.program,compile(gl.FRAGMENT_SHADER,fs));gl.linkProgram(this.program);if(!gl.getProgramParameter(this.program,gl.LINK_STATUS))throw Error(gl.getProgramInfoLog(this.program));this.position=gl.getAttribLocation(this.program,'position');this.uniforms=Object.fromEntries(['origin','heading','tilt','groundDrop'].map(n=>[n,gl.getUniformLocation(this.program,n)]));
 this.texture=gl.createTexture();gl.bindTexture(gl.TEXTURE_2D,this.texture);gl.texImage2D(gl.TEXTURE_2D,0,gl.RGBA,this.size,this.size,0,gl.RGBA,gl.UNSIGNED_BYTE,null);for(const p of [gl.TEXTURE_MIN_FILTER,gl.TEXTURE_MAG_FILTER])gl.texParameteri(gl.TEXTURE_2D,p,gl.NEAREST);for(const p of [gl.TEXTURE_WRAP_S,gl.TEXTURE_WRAP_T])gl.texParameteri(gl.TEXTURE_2D,p,gl.CLAMP_TO_EDGE);
 this.framebuffer=gl.createFramebuffer();gl.bindFramebuffer(gl.FRAMEBUFFER,this.framebuffer);gl.framebufferTexture2D(gl.FRAMEBUFFER,gl.COLOR_ATTACHMENT0,gl.TEXTURE_2D,this.texture,0);this.depth=gl.createRenderbuffer();gl.bindRenderbuffer(gl.RENDERBUFFER,this.depth);gl.renderbufferStorage(gl.RENDERBUFFER,gl.DEPTH_COMPONENT16,this.size,this.size);gl.framebufferRenderbuffer(gl.FRAMEBUFFER,gl.DEPTH_ATTACHMENT,gl.RENDERBUFFER,this.depth);if(gl.checkFramebufferStatus(gl.FRAMEBUFFER)!==gl.FRAMEBUFFER_COMPLETE)throw Error('Headlight shadow buffer unavailable');gl.bindFramebuffer(gl.FRAMEBUFFER,null);
 }
 draw(origin,heading,slope,meshes,groundMesh=meshes[0]){const gl=this.gl,angle=Math.atan(slope+.09);gl.bindFramebuffer(gl.FRAMEBUFFER,this.framebuffer);gl.viewport(0,0,this.size,this.size);gl.clearColor(1,1,1,1);gl.clear(gl.COLOR_BUFFER_BIT|gl.DEPTH_BUFFER_BIT);const dither=gl.isEnabled(gl.DITHER);gl.disable(gl.DITHER);gl.enable(gl.DEPTH_TEST);gl.disable(gl.BLEND);gl.disable(gl.CULL_FACE);gl.useProgram(this.program);gl.uniform3fv(this.uniforms.origin,origin);gl.uniform2f(this.uniforms.heading,Math.sin(heading),-Math.cos(heading));gl.uniform2f(this.uniforms.tilt,Math.cos(angle),Math.sin(angle));
 for(let i=0;i<gl.getParameter(gl.MAX_VERTEX_ATTRIBS);i++)gl.disableVertexAttribArray(i);gl.enableVertexAttribArray(this.position);
 for(const [i,m] of meshes.entries()){gl.uniform1f(this.uniforms.groundDrop,m===groundMesh?4:0);gl.bindBuffer(gl.ARRAY_BUFFER,m.b);gl.vertexAttribPointer(this.position,3,gl.FLOAT,false,36,0);if(m.index){gl.bindBuffer(gl.ELEMENT_ARRAY_BUFFER,m.index);gl.drawElements(gl.TRIANGLES,m.count,gl.UNSIGNED_SHORT,0);}else gl.drawArrays(gl.TRIANGLES,0,m.count);}
 gl.bindFramebuffer(gl.FRAMEBUFFER,null);if(dither)gl.enable(gl.DITHER);
 }
}
