import {discoveries,discoveryIds} from './discoveries.mjs';
import {WORLD,destinations} from './landscape.mjs';
import {delta,loadDelta,loadState,regionAt} from './regions.mjs';
import {feedbackSnapshot,feedbackEvents} from './feedback.mjs';
import {VEHICLES,vehicle,bestLapKey} from './vehicles.mjs';
import {create,update,recover,sampleNear,TUNE,nearest,ground,reverseAvailable,tuningFor,samples} from './sim.mjs';
import {Renderer} from './renderer.js';
const $=s=>document.querySelector(s),input={drive:false,brake:false,steer:0},keys=new Set(),touch=new Set();let paused=true,s,course,renderer,last=0,acc=0,resultShown=false,sound=true,audio,timeOfDay='day',solar=null,solarElapsed=0,solarRequest=false;
const vehicleKey='astra.expedition.prototype.vehicle.v1';let selected='sojourner';try{selected=vehicle(localStorage.getItem(vehicleKey)).id;}catch{}
const expeditionKey='astra.expedition.prototype.progress.v1';let progress={collected:[],visited:['Basin']},saveAt=0,loadRequested=false,retryAfter=0;
try{const saved=JSON.parse(localStorage.getItem(expeditionKey));if(saved&&Array.isArray(saved.collected)&&Array.isArray(saved.visited))progress=saved;}catch{}
function saveExpedition(){if(!s||s.mode==='trial')return;progress.collected=[...s.collected];progress.pose={x:s.x,y:s.y,heading:s.heading};progress.found=s.found;progress.discoveries=[...(s.discoveries??[])];try{localStorage.setItem(expeditionKey,JSON.stringify(progress));}catch{}}
addEventListener('pagehide',saveExpedition);
document.addEventListener('visibilitychange',()=>{if(document.hidden)saveExpedition();});
function primeDelta(){if(loadRequested||delta||performance.now()<retryAfter)return;loadRequested=true;loadDelta().catch(()=>{loadRequested=false;retryAfter=performance.now()+5000;});}
function knownFinds(){return s.mode==='trial'?discoveryIds(progress.discoveries,progress.found):s.discoveries;}
let mapTiles;
function mapTerrain(){if(mapTiles)return mapTiles;let out='';for(let y=WORLD.minY;y<WORLD.maxY;y+=200)for(let x=0;x<WORLD.width;x+=200){const z=ground(x+100,y+100),v=Math.min(1,z/230);out+=`<rect x="${x}" y="${y}" width="201" height="201" fill="rgb(${Math.round(132+v*67)},${Math.round(88+v*62)},${Math.round(62+v*43)})"/>`;}return mapTiles=out;}
function worldMap(){paused=true;clear();saveExpedition();$('#curtain').hidden=false;$('#panel').classList.remove('result-panel');$('#panel').innerHTML=`<h1>Mars expedition</h1><svg viewBox="0 ${WORLD.minY} ${WORLD.width} ${WORLD.height}" role="img" aria-label="Basin, delta, dark dunes and layered buttes" style="width:100%;height:min(42vh,380px);background:#81553e;border-radius:8px">${mapTerrain()}<path d="M960 470 Q3000 450 6200 490" stroke="#c9ab7a" stroke-width="35" fill="none"/>${(delta?.mesas??[]).map(poly=>`<polygon points="${poly.map(p=>p.join(',')).join(' ')}" fill="#c9915f"/>`).join('')}${samples.map((p,i)=>`<circle cx="${p.x}" cy="${p.y}" r="40" fill="${s.collected.includes(i)?'#83c9b0':'#f5d997'}"/>`).join('')}${discoveries.filter(d=>knownFinds().includes(d.id)).map(d=>`<path d="M${d.x} ${d.y-40} l40 40 -40 40 -40 -40Z" fill="#9bddcf"/>`).join('')}<circle cx="${s.x}" cy="${s.y}" r="45" fill="#d9fcff"/>${destinations.map(p=>`<text x="${p.x}" y="${p.y+230}" text-anchor="middle" fill="#f2e5ca" font-size="200">${({basin:"Basin",delta:"Delta",dunes:"Dunes",buttes:"Buttes",highlands:"Highlands",playa:"Flats",crater:"Crater"})[p.id]}</text>`).join('')}</svg><p>${s.collected.length} / ${samples.length} samples</p><button data-do="discoveries">Discoveries · ${knownFinds().length} / ${discoveries.length}</button><div class="actions"><button class="primary" data-do="resume">Resume</button>${destinations.filter(p=>progress.visited.includes(p.name)).map(p=>`<button data-travel="${p.id}">Return to ${p.name.toLowerCase()}</button>`).join('')}</div><p class="small">Explore north and south beyond the original route. Fictional route inspired by Jezero and Gale Crater; distances compressed.</p><details><summary>Terrain inspiration</summary><p class="small"><a href="https://www.jpl.nasa.gov/images/pia21269-curiositys-bagnold-dunes-campaign-two-types-of-dunes/" target="_blank" rel="noopener">Curiosity · Bagnold Dunes ↗</a><br><a href="https://www.jpl.nasa.gov/news/mars-rover-views-spectacular-layered-rock-formations/" target="_blank" rel="noopener">Curiosity · Murray Buttes ↗</a></p></details>`;}
function discoveryBook(){paused=true;clear();saveExpedition();$('#curtain').hidden=false;$('#panel').classList.remove('result-panel');const found=discoveries.filter(d=>knownFinds().includes(d.id));$('#panel').innerHTML=`<h1>Discoveries</h1><p>${found.length} / ${discoveries.length} collected</p>${found.map(d=>`<details class="field-notes"><summary>${d.name}</summary><p>${d.fact}</p><p class="small">${d.mission}</p><p>${d.history}</p><a href="${d.source}" target="_blank" rel="noopener noreferrer">NASA mission notes ↗</a></details>`).join('')}${found.length<discoveries.length?'<p class="small">Explore beside unusual rock formations. Stay near a find to collect it.</p>':''}<div class="actions"><button class="primary" data-do="resume">Keep exploring</button><button data-do="map">Map</button></div><p class="small">Fictional collection sites; real mission discoveries.</p>`;}
function travel(destination){const p=destinations.find(p=>p.id===destination);if(!p||!progress.visited.includes(p.name))return;if(destination!=='basin'&&!delta){primeDelta();return;}Object.assign(s,{x:p.x,y:p.y,heading:destination==='basin'?-Math.PI/2:Math.PI/2,v:0,vz:0,air:false,boost:0,charge:0,straight:0,cool:0,heat:0,collecting:-1,collectTime:0,done:false});s.z=ground(s.x,s.y);renderer.reset(s);resultShown=false;paused=false;$('#curtain').hidden=true;saveExpedition();}
const lapBests=new Map();
const solarTime=h=>`${String(Math.floor(h)).padStart(2,'0')}:${String(Math.floor(h%1*60)).padStart(2,'0')}`;
function requestSolar(action,value){if(parent===window)return;solarRequest=true;parent.postMessage({type:'rover-time',action,value},location.origin);}
addEventListener('message',e=>{if(e.source!==parent||e.origin!==location.origin)return;if(e.data?.type==='rover-solar'&&Number.isFinite(e.data.solar?.elevation)){solar=e.data.solar;solarElapsed=0;solarRequest=false;const elevation=solar.elevation*180/Math.PI;timeOfDay=elevation< -6?'night':elevation<8?(solar.solarHour<12?'dawn':'dusk'):'day';if(s){s.solar=solar;s.timeOfDay=timeOfDay;if(paused&&!resultShown&&document.querySelector('.rover-picker'))menu(s.t===0);}}else if(e.data?.type==='rover-solar-error'){solarRequest=false;const status=$('.solar-status');if(status)status.textContent=e.data.message;}});
const format=t=>{const cs=Math.round(t*100);return `${Math.floor(cs/6000)}:${((cs%6000)/100).toFixed(2).padStart(5,'0')}`;};
function clear(){keys.clear();touch.clear();Object.assign(input,{drive:false,brake:false,steer:0});document.querySelectorAll('.active').forEach(b=>b.classList.remove('active'));}
function cue(freq=650){if(!sound)return;try{audio??=new AudioContext();audio.resume();const o=audio.createOscillator(),g=audio.createGain();o.connect(g);g.connect(audio.destination);o.frequency.value=freq;g.gain.setValueAtTime(.025,audio.currentTime);g.gain.exponentialRampToValueAtTime(.001,audio.currentTime+.12);o.start();o.stop(audio.currentTime+.13);}catch{}}
function feedback(kind){
 const target=kind==='checkpoint'?$('.objective'):$('.boost');
 if(['checkpoint','ready','overheat'].includes(kind)){
  target.dataset.feedback=kind;target.getAnimations().forEach(a=>a.cancel());
  if(!matchMedia('(prefers-reduced-motion: reduce)').matches)target.animate([{boxShadow:kind==='overheat'?'0 0 0 3px #e5a278':'0 0 0 3px #c9e7a8'},{boxShadow:'0 0 0 0 transparent'}],{duration:750,easing:'ease-out'});
 }
 if(!sound)return;
 try{audio??=new AudioContext();audio.resume();
  const notes={checkpoint:[[660,0,.12],[880,.1,.18]],ready:[[740,0,.1],[990,.12,.2]],boost:[[180,0,.38,540]],warning:[[330,0,.12]],overheat:[[220,0,.18],[150,.15,.25]],sample:[[850,0,.18]]}[kind]??[];
  for(const [hz,delay,duration,to]of notes){const o=audio.createOscillator(),g=audio.createGain(),t=audio.currentTime+delay;o.type=kind==='boost'?'triangle':'sine';o.frequency.setValueAtTime(hz,t);if(to)o.frequency.exponentialRampToValueAtTime(to,t+duration);g.gain.setValueAtTime(0,t);g.gain.linearRampToValueAtTime(.035,t+.015);g.gain.exponentialRampToValueAtTime(.0001,t+duration);o.connect(g);g.connect(audio.destination);o.onended=()=>{o.disconnect();g.disconnect();};o.start(t);o.stop(t+duration+.02);}
 }catch{}
}
function restore(){s.collected=[...new Set(progress.collected.filter(i=>Number.isInteger(i)&&i>=0&&i<samples.length))];s.found=!!progress.found;s.discoveries=discoveryIds(progress.discoveries,s.found);const p=progress.pose;if(p&&[p.x,p.y,p.heading].every(Number.isFinite)&&p.x>=0&&p.x<=WORLD.width&&p.y>=WORLD.minY&&p.y<=WORLD.maxY){Object.assign(s,{x:p.x,y:p.y,heading:p.heading});s.z=ground(s.x,s.y);}}
function start(mode,roverId=selected){s=create(mode,course,roverId);if(mode!=='trial')restore();s.timeOfDay=timeOfDay;s.solar=solar;renderer.reset(s);clear();paused=false;resultShown=false;$('#curtain').hidden=true;$('#mode-title').textContent=mode==='trial'?'TIME TRIAL':mode==='free'?'FREE EXPLORATION':'COLLECT SAMPLES';cue(480);}
let previewRenderer,previewSurface;
function roverPreview(){const target=$('#rover-preview');if(!target||!course)return;
 if(!previewSurface){previewSurface=document.createElement('canvas');previewSurface.style.cssText='position:fixed;left:-10000px;width:520px;height:340px;pointer-events:none';previewSurface.setAttribute('aria-hidden','true');document.body.append(previewSurface);previewRenderer=new Renderer(previewSurface,null);}
 const pose=create('free',course,selected);Object.assign(pose,{x:100,y:600,heading:-.45,z:ground(100,600),solar});previewRenderer.reset(pose);previewRenderer.camera.h+=.4;previewRenderer.draw(pose,course,0);
 const ratio=previewSurface.width/520;target.width=400;target.height=180;target.getContext('2d').drawImage(previewSurface,149*ratio,140*ratio,222*ratio,100*ratio,0,0,400,180);target.setAttribute('aria-label',vehicle(selected).name+' in-game appearance');
}
function vehicleDetails(){const v=vehicle(selected),t=tuningFor(selected);return `<p class="rover-fact">NASA · landed ${v.year} · ${v.site} <a href="${v.source}" target="_blank" rel="noopener noreferrer" aria-label="${v.name} mission at NASA">↗</a></p><p class="rover-kit">${v.style} · Charge ${t.chargeSeconds}s · Boost ${t.boostSeconds}s · Overheat ${t.overheatCooldown}s</p>`;}
function roverPicker(first){return `<div class="rover-picker"><label for="rover-choice">${first?'Rover':'Next mission'}</label><select id="rover-choice">${VEHICLES.map(v=>`<option value="${v.id}" ${v.id===selected?'selected':''}>${v.name}</option>`).join('')}</select></div><canvas id="rover-preview" role="img"></canvas><div id="rover-details">${vehicleDetails()}</div>`;}
const instructions='<dl><dt>Drive</dt><dd>Hold W / ↑, or Drive. Steer with A D / ← →.</dd><dt>Brake / reverse</dt><dd>Hold Space, S / ↓, or Brake. At rest outside a sample zone, keep holding to reverse.</dd><dt>Samples</dt><dd>Stay inside a sample zone for 1.4 seconds to scan. You can keep moving; leaving resets progress.</dd><dt>Boost</dt><dd>Drive straight for 1 second, then fill the charge. Any turn resets buildup. Briefly release, then hold Drive again. Steer freely during boost. Release or brake to end it and begin charging again.</dd></dl>';
function menu(first=false){$('#panel').classList.remove('result-panel');paused=true;clear();$('#curtain').hidden=false;$('#panel').innerHTML=`<h1>${first?'Mars expedition':'Paused'}</h1>${roverPicker(first)}<div class="solar-date"><button type="button" data-time="hour" data-value="-1" aria-label="One hour earlier">−1h</button><button type="button" data-time="edit" id="solar-date-label">${solar?new Date(solar.epoch).toLocaleString('en-US',{timeZone:'UTC',month:'2-digit',day:'2-digit',year:'numeric',hour:'2-digit',minute:'2-digit',hour12:false})+' UTC':'Loading dated sky…'}</button><button type="button" data-time="hour" data-value="1" aria-label="One hour later">+1h</button><button type="button" data-time="now">Now</button></div><input id="solar-edit" type="datetime-local" aria-label="Date and time in UTC" min="1900-01-01T00:00" max="2100-12-31T23:59" hidden><p class="solar-status" role="status">${solar?'Jezero reference · solar time '+solarTime(solar.solarHour):'Open from the game’s Extras menu for dated sunlight.'}</p><div class="light-options" role="group" aria-label="Time of day">${['dawn','day','dusk','night'].map(t=>`<button data-light="${t}" ${solar?'':'disabled'} aria-pressed="${t===timeOfDay}">${t[0].toUpperCase()+t.slice(1)}</button>`).join('')}</div><div class="actions mission-actions">${first?'':'<button class="primary" data-do="resume">Resume</button>'}<button ${first?'class="primary"':''} data-do="collect">Collect samples</button><button data-do="map">Map</button><button data-do="discoveries">Discoveries</button><button data-do="free">Explore Mars</button></div><details class="control-help"><summary>Controls & boost</summary>${instructions}<p class="small">Every rover needs 1 second straight before charging. No normal cooldown. Overheating temporarily locks charging. Kit timings above apply to the next start. Esc: pause · R: recover.</p></details><div class="actions utility-actions">${first?'':'<button data-do="recover">Recover rover</button>'}<button data-do="reset-expedition">New expedition</button><button data-do="sound">Sound ${sound?'on':'off'}</button></div><p class="small prototype-note">Real rovers; fictional Mars route and boost kits. Stored boost works at night. Terrain and vehicle scale are illustrative.</p>`;roverPreview();$('#panel').querySelector('[data-do]').focus();}

function result(){
 paused=true;clear();resultShown=true;$('#curtain').hidden=false;
 const trial=s.mode==='trial',rover=vehicle(s.roverId);let record='';
 if(trial){
  let old=lapBests.get(s.roverId)??Infinity,saved=true;
  try{const n=Number(localStorage.getItem(bestLapKey(s.roverId))),stored=Number.isFinite(n)&&n>0?n:Infinity;old=Math.min(old,stored);
   if(Math.min(old,s.time)<stored)localStorage.setItem(bestLapKey(s.roverId),String(Math.min(old,s.time)));
  }catch{saved=false;}
  const best=Math.min(old,s.time),difference=s.time-old;lapBests.set(s.roverId,best);
  record=`<div class="lap-number">${format(s.time)}</div><div class="lap-record"><span>${saved?'Rover best':'Best this visit'}</span><b>${format(best)}</b></div>${Number.isFinite(old)?`<p class="lap-delta ${difference<0?'improved':''}">${Math.abs(difference)<.005?'Matched your best':difference<0?`${(-difference).toFixed(2)}s faster · New best`:`${difference.toFixed(2)}s from your best`}</p>`:''}${saved?'':'<p class="small">Lap could not be saved on this device.</p>'}`;
 }
 const collected=trial?'':`<div class="sample-manifest">${samples.map(p=>`<span><i>✓</i>${p.name}</span>`).join('')}</div><details class="field-notes"><summary>Field notes</summary>${samples.map(p=>`<p><b>${p.name}</b>${p.copy.replace(' Sample secured.','')}</p>`).join('')}</details>`;
 $('#panel').classList.add('result-panel');
 $('#panel').innerHTML=`<p class="result-place">${rover.name} · Jezero</p><h1>${trial?'Lap complete':'Eight samples secured'}</h1>${record}${collected}<div class="actions result-actions"><button class="primary" data-rover="${s.roverId}" data-do="trial">${trial?'Retry lap':'Explore the basin lap'}<span aria-hidden="true"> →</span></button><button data-do="continue">Keep exploring</button><button data-do="choose">Choose rover</button></div>${trial?'':'<p class="small next-lap">Sample collection complete</p>'}`;
 cue(880);$('#panel').querySelector('button').focus();
}

$('#panel').addEventListener('change',e=>{if(e.target.id!=='rover-choice')return;selected=vehicle(e.target.value).id;try{localStorage.setItem(vehicleKey,selected);}catch{}$('#rover-details').innerHTML=vehicleDetails();roverPreview();});
$('#panel').addEventListener('click',e=>{const light=e.target.closest('[data-light]')?.dataset.light;if(light){requestSolar('event',light);return;}const time=e.target.closest('[data-time]');if(time){if(time.dataset.time==='edit'){$('#solar-edit').hidden=!$('#solar-edit').hidden;if(solar)$('#solar-edit').value=solar.epoch.slice(0,16);$('#solar-edit').onchange=()=>{if($('#solar-edit').reportValidity()&&$('#solar-edit').value)requestSolar('set',$('#solar-edit').value+'Z');};}else requestSolar(time.dataset.time,Number(time.dataset.value));return;}const destination=e.target.closest('[data-travel]')?.dataset.travel;if(destination){travel(destination);return;}const a=e.target.closest('[data-do]')?.dataset.do;if(!a)return;if(['collect','trial','free'].includes(a))start(a,e.target.closest('[data-do]').dataset.rover??selected);else if(a==='map'){worldMap();}else if(a==='discoveries'){discoveryBook();}else if(a==='reset-expedition'){progress={collected:[],visited:['Basin']};start('free');saveExpedition();}else if(a==='choose'){selected=s.roverId;s=create('collect',course,selected);restore();s.solar=solar;s.timeOfDay=timeOfDay;renderer.reset(s);resultShown=false;menu(true);}else if(a==='resume'){$('#curtain').hidden=true;paused=false;clear();}else if(a==='recover'){recover(s,course);renderer.reset(s);paused=false;$('#curtain').hidden=true;}else if(a==='continue'){s.mode='free';s.done=false;resultShown=false;paused=false;$('#mode-title').textContent='FREE EXPLORATION';$('#curtain').hidden=true;}else if(a==='sound'){sound=!sound;menu(!s.started&&s.t===0);}});
$('#pause').onclick=()=>menu();
// Suppress browser selection/callout gestures on the game, including held controls.
for(const event of ['contextmenu','selectstart','dragstart'])document.addEventListener(event,e=>e.preventDefault());
function sync(){input.drive=keys.has('w')||keys.has('arrowup')||touch.has('drive');input.brake=keys.has(' ')||keys.has('s')||keys.has('arrowdown')||touch.has('secondary');input.steer=(keys.has('d')||keys.has('arrowright')||touch.has('right')?1:0)-(keys.has('a')||keys.has('arrowleft')||touch.has('left')?1:0);}
for(const id of ['left','right','secondary','drive']){const b=$('#'+id);b.onpointerdown=e=>{if(paused)return;e.preventDefault();b.setPointerCapture(e.pointerId);touch.add(id);b.classList.add('active');sync();};const release=()=>{touch.delete(id);b.classList.remove('active');sync();};b.onpointerup=release;b.onpointercancel=release;b.onlostpointercapture=release;}
addEventListener('keydown',e=>{const key=e.key.toLowerCase();if(key==='escape'){e.preventDefault();if(resultShown&&paused)return;if(!paused)menu();else if(s?.t>0){paused=false;$('#curtain').hidden=true;clear();}return;}if(paused)return;if(['w','s','a','d','arrowup','arrowdown','arrowleft','arrowright',' ','r'].includes(key)){e.preventDefault();if(key==='r'&&!e.repeat){recover(s,course);renderer.reset(s);}keys.add(key);sync();}});
addEventListener('keyup',e=>{keys.delete(e.key.toLowerCase());sync();});addEventListener('blur',()=>{if(s&&!paused)menu();else clear();});addEventListener('resize',()=>{if(s&&!paused)menu();});document.addEventListener('visibilitychange',()=>{if(document.hidden&&s&&!paused)menu();});
function hud(){const tune=s.tune??TUNE;$('.vehicle').textContent=vehicle(s.roverId).name.toUpperCase()+' · ASTRA KIT';const trial=s.mode==='trial',near=sampleNear(s);$('#solar-clock').textContent=solar?new Date(Date.parse(solar.epoch)+solarElapsed*1000).toISOString().slice(0,16).replace('T',' ')+' UTC · Mars '+solarTime(solar.solarHour):'Dated sky needs Extras';$('#goal').textContent=trial?`${s.nextGate<6?'GATE '+(s.nextGate+1)+' / 6':'FINISH'}`:'SAMPLES';$('#progress').textContent=trial?format(s.time):`${s.collected.length} / ${samples.length}`;$('#speed').textContent=Math.round(Math.abs(s.v)*.9);$('#secondary').textContent=reverseAvailable(s)?'Reverse':'Brake';$('#secondary').setAttribute('aria-label',reverseAvailable(s)?'Hold to reverse':'Hold to brake');$('#countdown').textContent=s.countdown>0?Math.ceil(s.countdown):'';$('#message').textContent=s.turnaround?'Auto-return · turning inland':s.boundary?'Leaving the expedition area · turn back':s.discoveryTarget?'Collecting find · '+Math.min(100,Math.floor(s.discoveryTime/1.4*100))+'%':s.collecting>=0?'Scanning · '+Math.min(100,Math.floor(s.collectTime/1.4*100))+'%':s.messageUntil>s.t?s.message:'';
 const loading=Math.min(1,(Math.min(s.straight,tune.straightSeconds)+s.charge*tune.chargeSeconds)/(tune.straightSeconds+tune.chargeSeconds));let label='Charging',value=Math.round(loading*100)+'%',fill=loading*100;if(s.boost){label='Boost';value=s.boost.toFixed(1)+' s';fill=s.boost/tune.boostSeconds*100;}else if(s.cool){label=s.overheated?'Overheated':'Cooling';value=s.cool.toFixed(1)+' s';fill=100*(1-s.cool/(s.overheated?tune.overheatCooldown:tune.cooldown));}else if(s.charge>=1){label='Boost ready';value='Lift → hold';}$('#boost-label').textContent=label;$('#boost-value').textContent=value;$('#charge').style.width=fill+'%';$('#heat').style.width=s.heat+'%';$('#heat-label').textContent=s.heat>=85?(s.boost?'High · release':'High'):s.heat>50?'Warm':'Low';$('.boost').style.borderColor=s.overheated?'#f08c70':s.heat>=85?'#e9bd78':'#b8d4b966';$('#heat').style.background=s.overheated?'#f18d72':'#dfbb78';}
function frame(time){const dt=Math.min(.05,(time-last)/1000||0);last=time;if(!paused){
 if(s.x>700)primeDelta();
 const region=regionAt(s.x,s.y);document.querySelector('.place').firstChild.textContent='MARS / '+region.toUpperCase();
 if(!progress.visited.includes(region)){progress.visited.push(region);s.message=region;s.messageUntil=s.t+4;saveExpedition();}
 if(Math.abs(s.t-saveAt)>1){saveAt=s.t;saveExpedition();}
 if(s.x>1850&&!delta){paused=true;clear();$('#curtain').hidden=false;$('#panel').innerHTML='<h1>Preparing the delta</h1><p>The next region is still loading.</p><div class="actions"><button data-do="resume">Try again</button><button data-travel="basin">Return to basin</button></div>';primeDelta();}
 if(!paused){solarElapsed+=dt;if(solar&&solarElapsed>=30&&!solarRequest)requestSolar('tick',solarElapsed);acc+=dt;while(acc>=1/60){const before=feedbackSnapshot(s),foundBefore=s.discoveries.length;update(s,input,1/60,course);if(s.discoveries.length>foundBefore){feedback('sample');saveExpedition();}acc-=1/60;for(const kind of feedbackEvents(before,s)){feedback(kind);if(kind==='checkpoint')renderer.gateFlash={...course.gates[before.gate],life:.7};}}if(s.done&&!resultShown)result();}}else acc=0;renderer.draw(s,course,dt);renderer.minimap($('#mini'),s,course);hud();requestAnimationFrame(frame);}
try{if(progress.pose?.x>700){await loadDelta();loadRequested=true;}const raw=await fetch('course.json').then(r=>{if(!r.ok)throw Error('Course unavailable');return r.json();});const path=document.createElementNS('http://www.w3.org/2000/svg','path');path.setAttribute('d',raw.path);const len=path.getTotalLength(),n=Math.ceil(len/4);const route=Array.from({length:n},(_,i)=>{const p=path.getPointAtLength(i/n*len);return {x:p.x,y:p.y};});const gate=(p,end=false)=>{const i=nearest(route,p[0],p[1]).i,a=route[(i-2+n)%n],b=route[(i+2)%n],d=Math.hypot(b.x-a.x,b.y-a.y);return {x:p[0],y:p[1],dx:(b.x-a.x)/d,dy:(b.y-a.y)/d,i:end?n:i};};course={route,gates:raw.gates.map(p=>gate(p)),finish:gate(raw.start,true)};
 const svg=await fetch('terrain.svg').then(r=>r.text());const doc=new DOMParser().parseFromString(svg,'image/svg+xml');doc.querySelectorAll('text, path[fill="#725341"]').forEach(e=>e.remove());doc.documentElement.setAttribute('width','1080');doc.documentElement.setAttribute('height','760');const url=URL.createObjectURL(new Blob([new XMLSerializer().serializeToString(doc)],{type:'image/svg+xml'}));const image=new Image();image.src=url;await image.decode();URL.revokeObjectURL(url);renderer=new Renderer($('#world'),image);s=create('collect',course,selected);restore();renderer.reset(s);if(solar){s.solar=solar;s.timeOfDay=timeOfDay;}menu(true);requestSolar('ready');requestAnimationFrame(frame);
 $('#mini').style.pointerEvents='auto';$('#mini').style.cursor='pointer';$('#mini').onclick=worldMap;
 window.__rover={get progress(){return progress},get regionState(){return loadState},get chunks(){return renderer.tileCache?.size??0},save:saveExpedition,map:worldMap,get state(){return s},course,input,start,step:(dt=1/60)=>update(s,input,dt,course),pause:()=>menu(),get paused(){return paused},preview:(name)=>{const views={start:[189,484,1.4186],channel:[280,480,1.5],mesa:[700,533,-.72],dunes:[943,685,0],overlook:[980,245,0]};const p=views[name];if(!p)return;start('free');Object.assign(s,{x:p[0],y:p[1],heading:p[2],z:ground(p[0],p[1])});renderer.reset(s);},recover:()=>recover(s,course)};
}catch(e){$('#error').hidden=false;$('#error').textContent='Could not open the rover prototype. Reload this page. '+e.message;console.error(e);}
